### ISSUE TITLE
Filebeat Palo Alto logs and dashboards.

### ISSUE THREAD

**Issue by marian-craciunescu** [elastic/beats#14590]
For confirmed bugs, please report:
- Version:  7.4.2
- Operating System:   Ubuntu
- Discuss Forum URL:
- Steps to Reproduce: 
1)Install filebeat and enable filebeat panw module
2) Setup index template and and load dashboard.

Mapping issue
`````
[2019-11-18T12:00:11,633][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"filebeat-7.4.2-v1-2019.11.18", :_type=>"_doc", :routing=>nil}, #<LogStash::Event:0x7e1e5092>], :response=>{"index"=>{"_index"=>"filebeat-7.4.2-v1-2019.11.18", "_type"=>"_doc", "_id"=>"ffV1f24Bt0y0UWddGl5b", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [event.start] of type [date] in document with id 'ffV1f24Bt0y0UWddGl5b'", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"failed to parse date field [2019/11/18 11:56:40] with format [strict_date_optional_time||epoch_millis]", "caused_by"=>{"type"=>"date_time_parse_exception", "reason"=>"date_time_parse_exception: Failed to parse with all enclosed parsers"}}}}}}

`````

To solve it modify the mapping tempalte for event.created and event.start
````
            "created" : {
              "type" : "date",
              "format": "yyyy/MM/dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
            }
````
ANOTHER ISSUE is that the dashboards saved search it's not retunring anything.
there is no `event.category` field .Neither an `event.action`

**Comment by gavmckee80** [comment]
Version: 7.6
Operating System: Ubuntu

Steps to Reproduce:
1) Install filebeat and send data to a Kafka topic
2)Configure logstash to subscribe to Kafka topic  
Setup index template and and load dashboard.

`[WARN ] 2020-03-03 21:10:11.837 [[main]>worker2] elasticsearch - Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"filebeat-7.6.0-2020.03.03", :routing=>nil, :_type=>"_doc"}, #<LogStash::Event:0x4450ae8f>], :response=>{"index"=>{"_index"=>"filebeat-7.6.0-2020.03.03", "_type"=>"_doc", "_id"=>"XPE8onABnHeYe0c2FAIw", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [event.created] of type [date] in document with id 'XPE8onABnHeYe0c2FAIw'. Preview of field's value: '2020/03/03 13:05:11'", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"failed to parse date field [2020/03/03 13:05:11] with format [strict_date_optional_time||epoch_millis]", "caused_by"=>{"type"=>"date_time_parse_exception", "reason"=>"Failed to parse with all enclosed parsers"}}}}}}`

Example document being sent to topic

`
{'@timestamp': '2020-03-03T21:58:08.597Z', '@metadata': {'beat': 'filebeat', 'type': '_doc', 'version': '7.6.0', 'pipeline': 'filebeat-7.6.0-panw-panos-pipeline', 'truncated': False}, 'event': {'start': '2020/03/03 13:57:36', 'duration': '0', 'module': 'panw', 'dataset': 'panw.panos', 'timezone': '+00:00', 'created': '2020/03/03 13:58:07', 'outcome': 'allow'}, 'fileset': {'name': 'panos'}, 'ecs': {'version': '1.4.0'}, 'log': {'source': {'address': '172.17.1.9:41000'}}, 'host': {'os': {'name': 'Ubuntu', 'kernel': '4.15.0-88-generic', 'codename': 'bionic', 'platform': 'ubuntu', 'version': '18.04.4 LTS (Bionic Beaver)', 'family': 'debian'}, 'id': '345562d34eab4dd5b70592d9487f70d4', 'name': 'elk-stack-test', 'containerized': False, 'hostname': 'elk-stack-test', 'architecture': 'x86_64'}, 'client': {'ip': '10.1.16.190', 'port': '57528', 'bytes': '88', 'packets': '1'}, 'destination': {'ip': '216.252.166.11', 'address': '216.252.166.11', 'nat': {'ip': '216.252.166.11', 'port': '53'}, 'port': '53', 'bytes': '88', 'packets': '1'}, 'agent': {'id': 'd871e074-3dbd-415e-adc5-cd7444ecfb80', 'version': '7.6.0', 'type': 'filebeat', 'ephemeral_id': '71ad7d75-3254-41ec-ba13-2b86d91b5115', 'hostname': 'elk-stack-test'}, 'tags': ['pan-os'], 'service': {'type': 'panw'}, '_temp_': {'message_type': 'TRAFFIC', 'message_subtype': 'end', 'generated_time': '2020/03/03 13:58:07', 'labels': '0x404019'}, 'panw': {'panos': {'ruleset': 'default', 'source': {'zone': 'corp', 'interface': 'ethernet1/3', 'nat': {'ip': '50.229.42.146', 'port': 12560}}, 'destination': {'zone': 'internet', 'interface': 'ethernet1/15', 'nat': {'port': 53, 'ip': '216.252.166.11'}}, 'flow_id': '618927', 'url': {'category': 'any'}, 'sequence_number': '152256243', 'network': {'nat': {'community_id': '1:KRaX+7VlbdSk8vkM1yM/ZA4TxLU='}}}}, 'network': {'packets': '2', 'community_id': '1:raRa/Odyd9s0aIpyhdquM+Rdh2Q=', 'application': 'dns', 'transport': 'udp', 'bytes': '223'}, 'input': {'type': 'syslog'}, 'observer': {'hostname': '900v-corp-fw-01a', 'serial_number': '016201014268'}, 'source': {'nat': {'ip': '50.229.42.146', 'port': '12560'}, 'port': '57528', 'bytes': '135', 'packets': '1', 'ip': '10.1.16.190', 'address': '10.1.16.190'}, 'server': {'ip': '216.252.166.11', 'port': '53', 'bytes': '135', 'packets': '1'}, 'message': '<14>1 2020-03-03T13:58:08-08:00 900v-corp-fw-01a.gh.st - - - -  1,2020/03/03 13:58:07,016201014268,TRAFFIC,end,2049,2020/03/03 13:58:07,10.1.16.190,216.252.166.11,50.229.42.146,216.252.166.11,default,,,dns,vsys1,corp,internet,ethernet1/3,ethernet1/15,test,2020/03/03 13:58:07,618927,1,57528,53,12560,53,0x404019,udp,allow,223,88,135,2,2020/03/03 13:57:36,0,any,0,152256243,0x0,10.0.0.0-10.255.255.255,United States,0,1,1,aged-out,0,0,0,0,,900v-corp-fw-01a,from-policy,,,0,,0,,N/A,0,0,0,0'}
`

**Comment by andrewkroh** [comment]
@gavmckee80 Data coming off of the Kafka topic needs to be processed by the module's Ingest Node pipeline. This is where the date is parsed. See https://www.elastic.co/guide/en/logstash/7.6/use-ingest-pipelines.html.

I think this is different from the original issue here because that should have been fixed and closed by https://github.com/elastic/beats/pull/13926.

**Comment by gavmckee80** [comment]
@andrewkroh Data is coming into the panw beat , so its being processed by the panw beat and being sent to Kafka , where I can dispatch it to various other pipelines .  I don't think I have to have this data processed again as logstash is subscribing to the topic with the beat data and shipping this off to elastic via an output directive .  It just looks like the event timestamp format for data coming from the panw beat is not in ISO format -

Examples of the event timestamps from the various modules 
netflow 2020-03-03T22:48:47.000Z
panw 2020/03/03 14:48:46

netflow is being ingested into Elastic fine.

**Comment by andrewkroh** [comment]
> I imagine if I send directly from beats to elastic without the logstash ingest I could recreate this issue.

If you remove Logstash it will work correctly because Filebeat will route the data to the proper Elasticsearch Ingest Node pipeline (specifically the one shown in the data you posted from the Kafka topic that has `@metadata.pipeline: filebeat-7.6.0-panw-panos-pipeline`).

If your Logstash's `elasticsearch` output does not have a `pipeline` configuration option then the data is not be routed to the Elasticsearch Ingest Node pipeline.

**Comment by gavmckee80** [comment]
Ok I'll test a bypass by going directly - but my question still stands - the JSON document that is sent from beats still does not have the correct timestamp format - but again I'll do a test.  
If I want to properly test the ingest into elastic from beats via Kafka I can pull the JSON document out of the queue and convert it to ISO UTC as follows

`
                event_created = arrow.get(record['event']['created'], tzinfo='US/Pacific').to('utc').isoformat().replace("+00:00", "Z")
                event_start = arrow.get(record['event']['start'], tzinfo='US/Pacific').to('utc').isoformat().replace("+00:00", "Z")
                record['event']['created'] = event_created
                record['event']['start'] = event_start

                producer.send('com.ghost.network.filebeat.filtered', record)
`

Once I do this Elastic indexes the data fine and I can view it in Kibana.  So I imagine if I go direct from beats to Elastic I'll have the indexing failure - but again I'll test for completeness.

**Comment by andrewkroh** [comment]
> but my question still stands - the JSON document that is sent from beats still does not have the correct timestamp format

The Elasticsearch Ingest Node pipeline named `filebeat-7.6.0-panw-panos-pipeline`, which is installed by Filebeat when `filebeat setup --pipelines` is executed, is responsible for parsing the timestamp and formatting it properly.

> So I imagine if I go direct from beats to Elastic I'll have the indexing failure

No, it should work correctly because Filebeat will ensure the event is processed by the Elasticsearch Ingest Node pipeline that's part of the module. Filebeat routes data to the pipeline when it makes its `_bulk` requests. If you use Kafka -> Logstash -> ES then you need to configure Logstash to set the pipeline as described [here](https://www.elastic.co/guide/en/logstash/7.6/use-ingest-pipelines.html).

**Comment by gavmckee80** [comment]
Tested by going directly from Filebeat to Elastic - I enabled debug level on filebeat , and I can see all of the panw syslog messages coming in .  When I sent this data to Elastic the index document count increases but I'm unable to see any documents under that index in Kibana.

So I test this a little more by changing the output to kafka so I can view the messages that filebeat is sending , example below
`
{"@timestamp":"2020-03-04T15:13:07.000Z","@metadata":{"beat":"filebeat","type":"_doc","version":"7.6.0","truncated":false,"pipeline":"filebeat-7.6.0-panw-panos-pipeline"},"panw":{"panos":{"ruleset":"default","source":{"zone":"corp","interface":"ethernet1/3","nat":{"ip":"50.229.42.146","port":0}},"destination":{"zone":"internet","interface":"ethernet1/15","nat":{"ip":"8.8.8.8","port":0}},"flow_id":"886579","url":{"category":"any"},"sequence_number":"154027086","network":{"nat":{"community_id":"1:1d1Smpw5wBv1TAqnkzog4zpPNao="}}}},"fileset":{"name":"panos"},"source":{"ip":"10.1.16.59","address":"10.1.16.59","nat":{"ip":"50.229.42.146","port":"0"},"port":"0","bytes":"74","packets":"1"},"client":{"bytes":"74","packets":"1","ip":"10.1.16.59","port":"0"},"server":{"ip":"8.8.8.8","port":"0","bytes":"74","packets":"1"},"network":{"transport":"icmp","bytes":"148","packets":"2","community_id":"1:CSg7DcWBV8wMdHG5nHgyUvcm8pE=","application":"ping"},"agent":{"type":"filebeat","ephemeral_id":"6e6c8861-66ce-415f-b595-6089a5706484","hostname":"elk-stack-test","id":"d871e074-3dbd-415e-adc5-cd7444ecfb80","version":"7.6.0"},"ecs":{"version":"1.4.0"},"tags":["pan-os"],"event":{"start":"2020/03/04 15:12:58","duration":"0","severity":6,"module":"panw","dataset":"panw.panos","timezone":"+00:00","created":"2020/03/04 15:13:06","outcome":"allow"},"log":{"source":{"address":"172.17.1.9:52731"}},"_temp_":{"generated_time":"2020/03/04 15:13:06","labels":"0x504019","message_type":"TRAFFIC","message_subtype":"end"},"destination":{"nat":{"ip":"8.8.8.8","port":"0"},"port":"0","bytes":"74","packets":"1","ip":"8.8.8.8","address":"8.8.8.8"},"message":"1,2020/03/04 15:13:06,016201014268,TRAFFIC,end,2049,2020/03/04 15:13:06,10.1.16.59,8.8.8.8,50.229.42.146,8.8.8.8,default,,,ping,vsys1,corp,internet,ethernet1/3,ethernet1/15,test,2020/03/04 15:13:06,886579,1,0,0,0,0,0x504019,icmp,allow,148,74,74,2,2020/03/04 15:12:58,0,any,0,154027086,0x0,10.0.0.0-10.255.255.255,United States,0,1,1,aged-out,0,0,0,0,,900v-corp-fw-01a,from-policy,,,0,,0,,N/A,0,0,0,0","syslog":{"facility_label":"user-level","priority":14,"severity_label":"Informational","facility":1},"service":{"type":"panw"},"input":{"type":"syslog"},"host":{"name":"elk-stack-test","containerized":false,"hostname":"elk-stack-test","architecture":"x86_64","os":{"family":"debian","name":"Ubuntu","kernel":"4.15.0-88-generic","codename":"bionic","platform":"ubuntu","version":"18.04.4 LTS (Bionic Beaver)"},"id":"345562d34eab4dd5b70592d9487f70d4"},"observer":{"serial_number":"016201014268","hostname":"900v-corp-fw-01a"},"hostname":"900v-corp-fw-01a.gh.st"}
`

Now I go back to filebeat configuration and send to Elastic again , but before I make sure everything is setup correctly.

`
-- enable the pipelines
gmckee@elk-stack-test:~$ sudo filebeat setup --pipelines -e
2020-03-04T18:11:35.106Z	INFO	instance/beat.go:622	Home path: [/usr/share/filebeat] Config path: [/etc/filebeat] Data path: [/var/lib/filebeat] Logs path: [/var/log/filebeat]
2020-03-04T18:11:35.107Z	INFO	instance/beat.go:630	Beat ID: d871e074-3dbd-415e-adc5-cd7444ecfb80
2020-03-04T18:11:35.118Z	INFO	[beat]	instance/beat.go:958	Beat info	{"system_info": {"beat": {"path": {"config": "/etc/filebeat", "data": "/var/lib/filebeat", "home": "/usr/share/filebeat", "logs": "/var/log/filebeat"}, "type": "filebeat", "uuid": "d871e074-3dbd-415e-adc5-cd7444ecfb80"}}}
2020-03-04T18:11:35.118Z	INFO	[beat]	instance/beat.go:967	Build info	{"system_info": {"build": {"commit": "6a23e8f8f30f5001ba344e4e54d8d9cb82cb107c", "libbeat": "7.6.0", "time": "2020-02-05T23:06:45.000Z", "version": "7.6.0"}}}
2020-03-04T18:11:35.118Z	INFO	[beat]	instance/beat.go:970	Go runtime info	{"system_info": {"go": {"os":"linux","arch":"amd64","max_procs":4,"version":"go1.13.7"}}}
2020-03-04T18:11:35.119Z	INFO	[beat]	instance/beat.go:974	Host info	{"system_info": {"host": {"architecture":"x86_64","boot_time":"2020-03-02T16:36:21Z","containerized":false,"name":"elk-stack-test","ip":["127.0.0.1/8","::1/128","192.168.122.104/24","fe80::5054:ff:fefb:be92/64","172.17.1.218/24","fe80::5054:ff:fee5:a155/64"],"kernel_version":"4.15.0-88-generic","mac":["52:54:00:fb:be:92","52:54:00:e5:a1:55"],"os":{"family":"debian","platform":"ubuntu","name":"Ubuntu","version":"18.04.4 LTS (Bionic Beaver)","major":18,"minor":4,"patch":4,"codename":"bionic"},"timezone":"UTC","timezone_offset_sec":0,"id":"345562d34eab4dd5b70592d9487f70d4"}}}
2020-03-04T18:11:35.120Z	INFO	[beat]	instance/beat.go:1003	Process info	{"system_info": {"process": {"capabilities": {"inheritable":null,"permitted":["chown","dac_override","dac_read_search","fowner","fsetid","kill","setgid","setuid","setpcap","linux_immutable","net_bind_service","net_broadcast","net_admin","net_raw","ipc_lock","ipc_owner","sys_module","sys_rawio","sys_chroot","sys_ptrace","sys_pacct","sys_admin","sys_boot","sys_nice","sys_resource","sys_time","sys_tty_config","mknod","lease","audit_write","audit_control","setfcap","mac_override","mac_admin","syslog","wake_alarm","block_suspend","audit_read"],"effective":["chown","dac_override","dac_read_search","fowner","fsetid","kill","setgid","setuid","setpcap","linux_immutable","net_bind_service","net_broadcast","net_admin","net_raw","ipc_lock","ipc_owner","sys_module","sys_rawio","sys_chroot","sys_ptrace","sys_pacct","sys_admin","sys_boot","sys_nice","sys_resource","sys_time","sys_tty_config","mknod","lease","audit_write","audit_control","setfcap","mac_override","mac_admin","syslog","wake_alarm","block_suspend","audit_read"],"bounding":["chown","dac_override","dac_read_search","fowner","fsetid","kill","setgid","setuid","setpcap","linux_immutable","net_bind_service","net_broadcast","net_admin","net_raw","ipc_lock","ipc_owner","sys_module","sys_rawio","sys_chroot","sys_ptrace","sys_pacct","sys_admin","sys_boot","sys_nice","sys_resource","sys_time","sys_tty_config","mknod","lease","audit_write","audit_control","setfcap","mac_override","mac_admin","syslog","wake_alarm","block_suspend","audit_read"],"ambient":null}, "cwd": "/home/gmckee", "exe": "/usr/share/filebeat/bin/filebeat", "name": "filebeat", "pid": 31693, "ppid": 31692, "seccomp": {"mode":"disabled","no_new_privs":false}, "start_time": "2020-03-04T18:11:34.050Z"}}}
2020-03-04T18:11:35.120Z	INFO	instance/beat.go:298	Setup Beat: filebeat; Version: 7.6.0
2020-03-04T18:11:35.121Z	INFO	[index-management]	idxmgmt/std.go:182	Set output.elasticsearch.index to 'filebeat-7.6.0' as ILM is enabled.
2020-03-04T18:11:35.122Z	INFO	elasticsearch/client.go:174	Elasticsearch url: http://localhost:9200
2020-03-04T18:11:35.123Z	INFO	[publisher]	pipeline/module.go:110	Beat name: elk-stack-test
2020-03-04T18:11:35.126Z	INFO	elasticsearch/client.go:174	Elasticsearch url: http://localhost:9200
2020-03-04T18:11:35.133Z	INFO	elasticsearch/client.go:757	Attempting to connect to Elasticsearch version 7.6.0
2020-03-04T18:11:35.236Z	INFO	[license]	licenser/es_callback.go:50	Elasticsearch license: Basic
2020-03-04T18:11:35.242Z	INFO	elasticsearch/client.go:174	Elasticsearch url: http://localhost:9200
2020-03-04T18:11:35.246Z	INFO	elasticsearch/client.go:757	Attempting to connect to Elasticsearch version 7.6.0
2020-03-04T18:11:35.350Z	INFO	[license]	licenser/es_callback.go:50	Elasticsearch license: Basic
2020-03-04T18:11:35.453Z	INFO	fileset/pipelines.go:134	Elasticsearch pipeline with ID 'filebeat-7.6.0-panw-panos-pipeline' loaded
2020-03-04T18:11:35.455Z	INFO	elasticsearch/client.go:174	Elasticsearch url: http://localhost:9200
2020-03-04T18:11:35.458Z	INFO	elasticsearch/client.go:757	Attempting to connect to Elasticsearch version 7.6.0
2020-03-04T18:11:35.560Z	INFO	[license]	licenser/es_callback.go:50	Elasticsearch license: Basic
2020-03-04T18:11:35.609Z	INFO	fileset/pipelines.go:134	Elasticsearch pipeline with ID 'filebeat-7.6.0-netflow-log-pipeline' loaded
2020-03-04T18:11:35.609Z	INFO	cfgfile/reload.go:264	Loading of config files completed.
2020-03-04T18:11:35.609Z	INFO	[load]	cfgfile/list.go:118	Stopping 2 runners 

`

Totally lost how to debug this further

**Comment by JAndritsch** [comment]
I'm seeing a similar problem using 8.2.2 ELK for the panos module. I'm sending a raw log event from panos to Filebeat that's configured to use the panw module. The module parses the event and then ships it to Logstash. Logstash simply passes the event through to Elasticsearch for indexing. When this happens, the following error occurs in Logstash logs:

```json
{
    "level": "WARN",
    "loggerName": "logstash.outputs.elasticsearch",
    "timeMillis": 1689087527631,
    "thread": "[beats-panw]>worker1",
    "logEvent": {
        "message": "Could not index event to Elasticsearch.",
        "status": 400,
        "action": [
            "create",
            {
                "_index": "logs-filebeat_panw_8.2.2-jandritsch",
                "pipeline": "filebeat-8.2.2-panw-panos-pipeline"
            },
            {
                "ecs": {
                    "version": "1.12.0"
                },
                "service": {
                    "type": "panw"
                },
                "destination": {
                    "port": "80",
                    "nat": {
                        "port": "0",
                        "ip": "0.0.0.0"
                    },
                    "ip": "204.232.231.46",
                    "packets": "0",
                    "address": "204.232.231.46",
                    "bytes": "0"
                },
                "event": {
                    "module": "panw",
                    "timezone": "+00:00",
                    "start": "2012/04/10 04:39:59",
                    "dataset": "panw.panos",
                    "created": "2012/10/30 09:46:12",
                    "original": "1,2012/10/30 09:46:12,01606001116,TRAFFIC,start,1,2012/04/10 04:39:58,192.168.0.2,204.232.231.46,0.0.0.0,0.0.0.0,rule1,crusher,,web-browsing,vsys1,trust,untrust,ethernet1/2,ethernet1/1,forwardAll,2012/04/10 04:39:59,11449,1,59324,80,0,0,0x200000,tcp,allow,78,78,0,1,2012/04/10 04:39:59,0,any,0,0,0x0,192.168.0.0-192.168.255.255,United States,0,1,0",
                    "duration": "0"
                },
                "agent": {
                    "ephemeral_id": "8876b7ca-d13e-49e3-ad0c-65c11fe2abb9",
                    "id": "fc5c77c5-7291-4ea1-8ed3-cc1e532875f6",
                    "type": "filebeat",
                    "name": "PRD-VIRT-RHL-33.AD.VERVEINDUSTRIAL.COM",
                    "version": "8.2.2"
                },
                "fileset": {
                    "name": "panos"
                },
                "network": {
                    "packets": "1",
                    "application": "web-browsing",
                    "transport": "tcp",
                    "bytes": "78"
                },
                "message": "1,2012/10/30 09:46:12,01606001116,TRAFFIC,start,1,2012/04/10 04:39:58,192.168.0.2,204.232.231.46,0.0.0.0,0.0.0.0,rule1,crusher,,web-browsing,vsys1,trust,untrust,ethernet1/2,ethernet1/1,forwardAll,2012/04/10 04:39:59,11449,1,59324,80,0,0,0x200000,tcp,allow,78,78,0,1,2012/04/10 04:39:59,0,any,0,0,0x0,192.168.0.0-192.168.255.255,United States,0,1,0",
                "input": {
                    "type": "syslog"
                },
                "client": {
                    "port": "59324",
                    "packets": "1",
                    "ip": "192.168.0.2",
                    "nat": {
                        "port": "0",
                        "ip": "0.0.0.0"
                    },
                    "user": {
                        "name": "crusher"
                    },
                    "bytes": "78"
                },
                "data_stream": {
                    "dataset": "filebeat_panw_8.2.2",
                    "namespace": "jandritsch",
                    "type": "logs"
                },
                "@version": "1",
                "@timestamp": "2023-11-30T16:09:08Z",
                "source": {
                    "port": "59324",
                    "nat": {
                        "port": "0",
                        "ip": "0.0.0.0"
                    },
                    "ip": "192.168.0.2",
                    "packets": "1",
                    "address": "192.168.0.2",
                    "user": {
                        "name": "crusher"
                    },
                    "bytes": "78"
                },
                "panw": {
                    "panos": {
                        "destination": {
                            "zone": "untrust",
                            "nat": {
                                "port": 0,
                                "ip": "0.0.0.0"
                            },
                            "interface": "ethernet1/1"
                        },
                        "sub_type": "start",
                        "virtual_sys": "vsys1",
                        "url": {
                            "category": "any"
                        },
                        "flow_id": "11449",
                        "source": {
                            "zone": "trust",
                            "nat": {
                                "port": 0,
                                "ip": "0.0.0.0"
                            },
                            "interface": "ethernet1/2"
                        },
                        "type": "TRAFFIC",
                        "ruleset": "rule1",
                        "action": "allow",
                        "sequence_number": "0"
                    }
                },
                "hostname": "PA-220",
                "observer": {
                    "serial_number": "01606001116",
                    "ingress": {
                        "zone": "trust",
                        "interface": {
                            "name": "ethernet1/2"
                        }
                    },
                    "product": "PAN-OS",
                    "type": "firewall",
                    "vendor": "Palo Alto Networks",
                    "egress": {
                        "zone": "untrust",
                        "interface": {
                            "name": "ethernet1/1"
                        }
                    }
                },
                "tags": [
                    "pan-os",
                    "forwarded",
                    "beats_input_codec_plain_applied"
                ],
                "server": {
                    "port": "80",
                    "nat": {
                        "port": "0",
                        "ip": "0.0.0.0"
                    },
                    "ip": "204.232.231.46",
                    "bytes": "0",
                    "packets": "0"
                },
                "log": {
                    "source": {
                        "address": "10.2.96.36:50067"
                    }
                }
            }
        ],
        "response": {
            "create": {
                "_index": ".ds-logs-filebeat_panw_8.2.2-jandritsch-2023.07.11-000001",
                "_id": "vpt2RYkBlqKEWI4OSpHM",
                "status": 400,
                "error": {
                    "type": "mapper_parsing_exception",
                    "reason": "failed to parse field [event.created] of type [date] in document with id 'vpt2RYkBlqKEWI4OSpHM'. Preview of field's value: '2012/10/30 09:46:12'",
                    "caused_by": {
                        "type": "illegal_argument_exception",
                        "reason": "failed to parse date field [2012/10/30 09:46:12] with format [strict_date_optional_time||epoch_millis]",
                        "caused_by": {
                            "type": "date_time_parse_exception",
                            "reason": "Failed to parse with all enclosed parsers"
                        }
                    }
                }
            }
        }
    }
}
```

It looks like the ingest pipeline is supposed to parse and format the `event.created` and `event.started` into the correct formats but for whatever reason does not. If I test this event directly against the ingest pipeline via simulate API everything works. The `event.created` and `event.started` fields are correctly reformatted from `yyyy/MM/dd HH:mm:ss`. But for some reason this doesn't work in practice.

If I remove the `event.created` and `event.started` fields from the incoming event before attempting to index with the pipeline ID then everything works. Any ideas as to what's going on here?
