### ISSUE TITLE
[Winlogbeat] CLI Values to ECS process.command_line

### ISSUE THREAD

**Issue by neu5ron** [elastic/beats#16072]
Currently in the winlogbeat modules for ECS there is a field for [process.command_line](https://github.com/elastic/ecs/blob/68afbb82c721206c6473cce4f3ff6186f713ed93/schemas/process.yml#L105) which stores the entire command line. As of right now the winlogbeat modules split the command line into `process.args` which removes the ability to analyze the command line in its original entirety.
Currently this affects Machine Learning jobs, watcher queries, and other queries/rules in their accuracy to match the values.

The solution appears simple, just need to copy the command line value before it gets process into `process.args` split function.

In the winlogbeat security module copy before this line:
https://github.com/elastic/beats/blob/bb70dc71135d74ee7cabd03205f18f6b62f122ad/x-pack/winlogbeat/module/security/config/winlogbeat-security.js#L1314

In the winlogbeat sysmon module, copy the value to process.command_line before this line
https://github.com/elastic/beats/blob/bb70dc71135d74ee7cabd03205f18f6b62f122ad/x-pack/winlogbeat/module/sysmon/config/winlogbeat-sysmon.js#L407
or this line
https://github.com/elastic/beats/blob/bb70dc71135d74ee7cabd03205f18f6b62f122ad/x-pack/winlogbeat/module/sysmon/config/winlogbeat-sysmon.js#L249

This may need ported for auditbeat and filebeat too.

**Comment by neu5ron** [comment]
related in a way that may show the importance of this field and matching with EQL and endpoint https://github.com/elastic/ecs/issues/647

**Comment by rw-access** [comment]
@neu5ron was this fixed in https://github.com/elastic/beats/pull/17327?

**Comment by neu5ron** [comment]
@rw-access I dont believe so, does not appear to be extended to the Security module. Also, I think the same may still apply for any linux (or other) modules.

**Comment by neu5ron** [comment]
creating recent activity, not sure should be closed as stale - still exists.

**Comment by neu5ron** [comment]
bumping this again, still the same issue. 
can just create a catch all at the end of these beats pipelines and ingest pipelines to copy process.args(joined by single white space) to process.command_line ?

@rw-access thoughts?

**Comment by rw-access** [comment]
depends on your needs, but I wouldn't recommend it if you plan on writing detection logic for that field. it wouldn't preserve any of the original quoting or escapes

**Comment by agg-mb** [comment]
👍
