### ISSUE TITLE
No activity logs shown and Mac Mojave agent starts up but then goes to Offline status (8.0.0 Kibana cloud)

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#22224]
**Kibana version:**
Kibana: 8.0.0 Snapshot cloud environment

**Elasticsearch version:**
Elasticsearch: 8.0.0 Snapshot cloud environment

**Host OS and Browser version:**
Linux , All

**Original install method (e.g. download page, yum, from source, etc.):**
8.0.0 Snapshot cloud environment

**Description**
No activity logs and agent goes to Offline status in UI on 8.0.0 snapshot Kibana cloud environment

**Preconditions**
1. Test Case Id https://elastic.testrail.io/index.php?/cases/view/22506 need to be executed (8.0.0-snapshot Kibana cloud environment should be available).
2. Login into the above Kibana environment(with commit db0816f4a1fb7fb5a24106be53c86e5f8c5404e1) with 'elastic' superuser.
3. Endpoint integration should be added in Default Policy
4. 8.0.0 Agent should be downloaded from below location:
  https://snapshots.elastic.co/8.0.0-c4b68cea/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz
  
5. Above elastic agent should be installed with ./elastic-agent install command.

**Steps to Reproduce**
1. Navigate to Agents tab in Kibana
2. Click on prerequisite host
3. Observe that no activity logs are displayed.
4. Wait for some time and observe that agent goes to Offline status. 

**Test data**
N/A

**Impacted Test case id**
N/A

**Actual Result**
No activity logs and agent goes to Offline status in UI on 8.0.0 snapshot Kibana cloud environment

**Expected Result**
Agent in Online status and Activity logs should be displayed on 8.0.0 snapshot Kibana cloud environment

**What's working**
 - N/A

**What's not working**
 - N/A
 
**Screenshot**
![no_activity_logs_offline](https://user-images.githubusercontent.com/59917944/97436339-df05be00-1947-11eb-9663-d71dffecd7f1.jpg)

**Logs**
N/A

**Comment by rahulgupta-qasource** [comment]
@vipulsrivastava-qasource Please review the bug.

**Comment by vipulsrivastava-qasource** [comment]
Reviewed and Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
I'm not seeing this in my test of 8.0 Kibana (same Kibana build) but with a newer Agent.  I think the above is more than a day old, the current is: https://snapshots.elastic.co/8.0.0-36160761

**Comment by EricDavisX** [comment]
I think the staging environment was just struggling (out of memory or not enough CPU to go around to all of the environments that existed) - I see that the team logged: https://github.com/elastic/beats/issues/22226 for 7.10 line and
https://github.com/elastic/cloud/issues/69006 on the cloud side which was later closed... tho I was seeing slightly slower than usual performance on my Kibana cloud stack, which is not formal but seems reason to believe staging was just struggling.  

I expect this isn't a product bug and we can wait till tomorrow to confirm and then close it.

**Comment by rahulgupta-qasource** [comment]
Hi @EricDavisX 

Thank you for sharing the feedback.

We are blocked to validate this ticket on 8.0.0-snapshot kibana cloud build as we are unable to deploy it from [staging environment](https://staging.found.no/) due to reopened bug [#69006](https://github.com/elastic/cloud/issues/69006)

Once bug [#69006](https://github.com/elastic/cloud/issues/69006) is fixed, we will validate this ticket.

**Comment by EricDavisX** [comment]
in QA sync meeting today, Manish confirmed his access was restored to cloud staging, and so he created a new environment of 8.0 that we can use tomorrow to test if it is not working for Rahul or others to create their own.  The 69006 is being follow up as an incident on cloud side, so it is likely to be more permanently fixed soon.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX,

Thank you for the update.

We have re-validated this issue on 8.0 snapshot Kibana cloud build and found it still reproducible.[Below are build detail]

**Kibana Commit:** d869f558c3bd2736702a393b8e7f6b487ce5d0a6
**Build:** 37629
**Artifact link:** https://artifacts-api.elastic.co/v1/search/8.0.0-SNAPSHOT/elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz
**OS** : MacOS Mojave 10.14

Preconditions:
- 8.0.0-snapshot Kibana cloud environment should be available.
- Endpoint integration should be added in Default Policy

Steps to Reproduce:
- Install Elastic agent with ./elastic-agent install command successfully.
- Navigate to Agents tab in Kibana.
- Click on prerequisite host showing enrolling>online.
- Observe that no activity logs are displayed.
- Wait for few minutes say '2 minutes' and observe that agent goes to Offline status.

Screenshot:
![22224_error](https://user-images.githubusercontent.com/72375798/97697090-827fdb80-1acc-11eb-94f1-6d5b10ab0fd1.png)

**Comment by EricDavisX** [comment]
@rahulgupta-qasource and @dikshachauhan-qasource can I ask for the comparison tests to be cited for us?
 - on the same vm (you can roll back to a snapshot?) and try with the same 7.9.3 GA Agent / stack-kibana does it work?

 - on a different OS does the same build of Agent / Kibana fail?  We'd love to have help narrowing it down.
I can add that the Kibana Endpoint demo server is up with Windows Agents via 'install' subcommand with Endpoint of the latest 8.0 snapshot and they are ok, and it has Linux .rpm install with Agent/Endpoint that is also ok.  
...So I'm wondering if it is specific to a setting on the VM that we aren't accounting for.  Can you post what exact template the VM is based on, if it is indeed a vm in the Endgame vSphere cluster?

I had missed initially that it was only with Endpoint enabled that Agent goes off-line.  @ferullo in what situations would you think Endpoint would impact Agent as such?  @ph

**Comment by rahulgupta-qasource** [comment]
Hi EricDavisX

Thank you for sharing the feedback.

We have validated the scenario for 7.9.3 GA agent and 7.9.3 kibana cloud environment and found that issue is not occurring with 7.9.3 BC1 agent and Kibana

Observed that agent remains in Online status(even after waiting for 02 min) and activity logs are displayed.

Moreover, we are unable to validate on 8.0-snapshot cloud kibana environment as 'Unhealthy deployment' error is displayed on deploying it. We have reopened bug https://github.com/elastic/cloud/issues/69006 for the same.

**Comment by EricDavisX** [comment]
the cloud team is spinning up another investigation into staging, they are aware of the problems (it is unavailable entirely as I see it at this point).

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX

We have re-validated this scenario on 8.0 snapshot Kibana cloud build on different operating systems. Observations are as below:

[Below are build detail]

```
Kibana Commit: 228387cb6e3cdc35123f5a8bc40d3ad87d4f9e52
Build: 38085
Artifact link: https://artifacts-api.elastic.co/v1/search/8.0.0-SNAPSHOT/elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz
MAC Template: qa-mac-mojave-clone-base
```

Precondition: Endpoint integration should be added in Default Policy.

We have followed same steps as mentioned in defect summary.

**Observation 1 on MAC:**
- Agent comes online for a minute.
- No activity logs generated.
- Agent goes offline.

Screenshot:
![#22224_observation23nov](https://user-images.githubusercontent.com/72375798/99965836-73ced080-2dbb-11eb-9fb1-f855d20e9794.jpg)

**Observation 2 on Windows:**
While validating it on **windows** , we found it working fine:
Artifact link used: https://snapshots.elastic.co/8.0.0-dde0da96/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip

Screenshot:
![#22224_observation2_onwindows](https://user-images.githubusercontent.com/72375798/99965855-7b8e7500-2dbb-11eb-8bc1-f43f917f3c86.png)

**Comment by EricDavisX** [comment]
I am testing on a version of Mojave in Endgame vSphere and I see it working, as tested on 7.11 latest build.  I also tested my local mac and it works.

This issue has lived thru almost a month now, with confirmed 'cloud' issues impacting in between Agent side review, if we can't find a way to reproduce it soon I think the best course is to log a new ticket with more clarity and start testing over, with lots of comparison data, from the same Kibana and from Linux .tar and macOS tar and same vm template where needed.  The versions tested were 10.14.1 and 10.15.7

I don't have an answer as to what is causing our differences, my only thought now is to ask... Can you try a different mac OS template like sierra or high sierra etc and report back?  

I did hear that some signing work was completed recently, but I didn't see the ticket # to know when we could compare if it was merged, but your testing just yesterday is extremely recent so I'm skeptical that would impact, but I wanted to mention it as my only lead.  

I guess, one more item to try.  You could try to connect to my cloud Kibana 7.11 build which is seen as working now:
https://5b98001d272449f28f0d24f8d0bc749c.us-east-1.aws.staging.foundit.no:9243/app/fleet#/
 I'll post you the UID/PWD in slack.

**Comment by rahulgupta-qasource** [comment]
Hi @EricDavisX 

We have validated the ticket with 7.11.0-SNAPSHOT darwin agent on above 7.11.0-SNAPSHOT Kibana cloud environment https://5b98001d272449f28f0d24f8d0bc749c.us-east-1.aws.staging.foundit.no:9243/app/fleet# (with commit 968b6e5104013e02b55fefaa27793f878764361f) with macOS mojave 10.14.1

macOS Agent: https://snapshots.elastic.co/7.11.0-917eed6c/downloads/beats/elastic-agent/elastic-agent-7.11.0-SNAPSHOT-darwin-x86_64.tar.gz

and found that agent remains in Online status(even after waiting for sometime) and agent logs are displayed.

Screenshot:
![mac_screenshot](https://user-images.githubusercontent.com/59917944/100210237-ca115000-2f30-11eb-8634-cf48b1e43cca.jpg)

Hence, closing the bug.
