### ISSUE TITLE
[Ingest Manager]: 'default' is displayed at data_stream.namespace on discover tab instead of non-default policy namespace

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#23020]
Kibana version:
Kibana:8.0.0 snapshot Cloud environment

Elasticsearch version:
Elasticsearch:  8.0.0 snapshot Cloud environment  

Host OS and Browser version:
Windows 10, All

Original install method (e.g. download page, yum, from source, etc.):
8.0.0 snapshot Cloud environment 

While exploratory testing, we have validate a scenario as per [ticket summary](https://github.com/elastic/beats/issues/21796#issue-721470067) on 8.0.0 snapshot kibana cloud build. Build details are as follows:
```
BUILD 38666
COMMIT 62e79eec7011cb8ffa6f1c9626f4f989656ddad1
Artifact link: https://artifacts-api.elastic.co/v1/search/8.0.0-SNAPSHOT/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip
```

Preconditions:
- Create a test policy say 'test1' with namespace : test_1 other than default
- System and endpoint integration should be added to test policy.

Steps to reproduce:
1. Installed agent using 'test1' policy.
2. Wait for agent and endpoint logs to generate successfully.
3. Go to discover tab.
4. Select Logs*- . Apply 'event.dataset : "elastic_agent.endpoint_security"'filter at KQL query.

**Reference link:**
https://elastic.testrail.io/index.php?/cases/view/35320

**Actual result :**
'default' is displayed at data_stream.namespace on discover tab instead of  instead of 'test_1'

**Expected result:**
'test_1' should be displayed at data_stream.namespace on discover tab after applying 'event.dataset : "elastic_agent.endpoint_security"'filter at KQL query.

Screenshot:
![21796_observation](https://user-images.githubusercontent.com/72375798/101629796-e4c2e900-3a47-11eb-8138-bfaf8744a4f4.jpg)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource please review

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
@ruflin @ph this sounds like namespace isn't being carried thru the whole stack.  That would feel high priority to me, until we know otherwise.  Do you want to review or assign someone?

**Comment by ph** [comment]
@EricDavisX I have some doubts here, I am more sure it's in the fleet side, because I would assume that we send the right information for every integration policy generated. 

@manishgupta-qasource Can you add to this issue the YAML configuration from the Agent policy, I believe the _namespace_ is added to the input section but **endpoint** doesn't respect that. 

@kevinlog might know too?

**Comment by dikshachauhan-qasource** [comment]
Hi @ph 

Please find elastic-agent.yml configuration from the Agent policy 'test1' on 8.0.0 snapshot kibana cloud here as follows.

```
id: 1c3f7390-3ac9-11eb-b78c-29a4f5b612b8
revision: 2
outputs:
  default:
    type: elasticsearch
    hosts:
      - 'https://962a698d578443eaa25fa40c78c88d4f.us-central1.gcp.foundit.no:443'
agent:
  monitoring:
    enabled: true
    use_output: default
    logs: true
    metrics: true
inputs:
  - id: d7fa66e4-07a1-47ac-bd2b-e7fc51db7238
    name: system-1
    revision: 1
    type: logfile
    use_output: default
    meta:
      package:
        name: system
        version: 0.9.2
    data_stream:
      namespace: test_1
    streams:
      - id: logfile-system.auth-d7fa66e4-07a1-47ac-bd2b-e7fc51db7238
        data_stream:
          dataset: system.auth
          type: logs
        paths:
          - /var/log/auth.log*
          - /var/log/secure*
        exclude_files:
          - .gz$
        multiline:
          pattern: ^\s
          match: after
        processors:
          - add_locale: null
          - add_fields:
              target: ''
              fields:
                ecs.version: 1.5.0
      - id: logfile-system.syslog-d7fa66e4-07a1-47ac-bd2b-e7fc51db7238
        data_stream:
          dataset: system.syslog
          type: logs
        paths:
          - /var/log/messages*
          - /var/log/syslog*
        exclude_files:
          - .gz$
        multiline:
          pattern: ^\s
          match: after
        processors:
          - add_locale: null
          - add_fields:
              target: ''
              fields:
                ecs.version: 1.5.0
  - id: d7fa66e4-07a1-47ac-bd2b-e7fc51db7238
    name: system-1
    revision: 1
    type: system/metrics
    use_output: default
    meta:
      package:
        name: system
        version: 0.9.2
    data_stream:
      namespace: test_1
    streams:
      - id: system/metrics-system.cpu-d7fa66e4-07a1-47ac-bd2b-e7fc51db7238
        data_stream:
          dataset: system.cpu
          type: metrics
        metricsets:
          - cpu
        cpu.metrics:
          - percentages
          - normalized_percentages
        period: 10s
      - id: system/metrics-system.diskio-d7fa66e4-07a1-47ac-bd2b-e7fc51db7238
        data_stream:
          dataset: system.diskio
          type: metrics
        metricsets:
          - diskio
        diskio.include_devices: null
        period: 10s
      - id: system/metrics-system.filesystem-d7fa66e4-07a1-47ac-bd2b-e7fc51db7238
        data_stream:
          dataset: system.filesystem
          type: metrics
        metricsets:
          - filesystem
        period: 1m
        processors:
          - drop_event.when.regexp:
              system.filesystem.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - id: system/metrics-system.fsstat-d7fa66e4-07a1-47ac-bd2b-e7fc51db7238
        data_stream:
          dataset: system.fsstat
          type: metrics
        metricsets:
          - fsstat
        period: 1m
        processors:
          - drop_event.when.regexp:
              system.fsstat.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - id: system/metrics-system.load-d7fa66e4-07a1-47ac-bd2b-e7fc51db7238
        data_stream:
          dataset: system.load
          type: metrics
        metricsets:
          - load
        period: 10s
      - id: system/metrics-system.memory-d7fa66e4-07a1-47ac-bd2b-e7fc51db7238
        data_stream:
          dataset: system.memory
          type: metrics
        metricsets:
          - memory
        period: 10s
      - id: system/metrics-system.network-d7fa66e4-07a1-47ac-bd2b-e7fc51db7238
        data_stream:
          dataset: system.network
          type: metrics
        metricsets:
          - network
        period: 10s
        network.interfaces: null
      - id: system/metrics-system.process-d7fa66e4-07a1-47ac-bd2b-e7fc51db7238
        data_stream:
          dataset: system.process
          type: metrics
        metricsets:
          - process
        period: 10s
        process.include_top_n.by_cpu: 5
        process.include_top_n.by_memory: 5
        process.cmdline.cache.enabled: true
        process.cgroups.enabled: false
        process.include_cpu_ticks: false
        processes:
          - .*
      - id: >-
          system/metrics-system.process_summary-d7fa66e4-07a1-47ac-bd2b-e7fc51db7238
        data_stream:
          dataset: system.process_summary
          type: metrics
        metricsets:
          - process_summary
        period: 10s
      - id: >-
          system/metrics-system.socket_summary-d7fa66e4-07a1-47ac-bd2b-e7fc51db7238
        data_stream:
          dataset: system.socket_summary
          type: metrics
        metricsets:
          - socket_summary
        period: 10s
      - id: system/metrics-system.uptime-d7fa66e4-07a1-47ac-bd2b-e7fc51db7238
        data_stream:
          dataset: system.uptime
          type: metrics
        metricsets:
          - uptime
        period: 10s
  - id: 6493f0d0-7c52-40a2-b4c1-e0e5c57f38ad
    name: endpoint1
    revision: 1
    type: endpoint
    use_output: default
    meta:
      package:
        name: endpoint
        version: 0.17.0-dev.4
    data_stream:
      namespace: test_1
    artifact_manifest:
      manifest_version: 1.0.0
      schema_version: v1
      artifacts:
        endpoint-exceptionlist-macos-v1:
          encryption_algorithm: none
          decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
          decoded_size: 14
          encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
          encoded_size: 22
          relative_url: >-
            /api/endpoint/artifacts/download/endpoint-exceptionlist-macos-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
          compression_algorithm: zlib
        endpoint-exceptionlist-windows-v1:
          encryption_algorithm: none
          decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
          decoded_size: 14
          encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
          encoded_size: 22
          relative_url: >-
            /api/endpoint/artifacts/download/endpoint-exceptionlist-windows-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
          compression_algorithm: zlib
        endpoint-trustlist-macos-v1:
          encryption_algorithm: none
          decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
          decoded_size: 14
          encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
          encoded_size: 22
          relative_url: >-
            /api/endpoint/artifacts/download/endpoint-trustlist-macos-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
          compression_algorithm: zlib
        endpoint-trustlist-windows-v1:
          encryption_algorithm: none
          decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
          decoded_size: 14
          encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
          encoded_size: 22
          relative_url: >-
            /api/endpoint/artifacts/download/endpoint-trustlist-windows-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
          compression_algorithm: zlib
        endpoint-trustlist-linux-v1:
          encryption_algorithm: none
          decoded_sha256: d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
          decoded_size: 14
          encoded_sha256: f8e6afa1d5662f5b37f83337af774b5785b5b7f1daee08b7b00c2d6813874cda
          encoded_size: 22
          relative_url: >-
            /api/endpoint/artifacts/download/endpoint-trustlist-linux-v1/d801aa1fb7ddcc330a5e3173372ea6af4a3d08ec58074478e85aa5603e926658
          compression_algorithm: zlib
    policy:
      windows:
        events:
          dll_and_driver_load: true
          dns: true
          file: true
          network: true
          process: true
          registry: true
          security: true
        malware:
          mode: prevent
        popup:
          malware:
            enabled: true
            message: ''
        logging:
          file: info
        antivirus_registration:
          enabled: false
      mac:
        events:
          process: true
          file: true
          network: true
        malware:
          mode: prevent
        popup:
          malware:
            enabled: true
            message: ''
        logging:
          file: info
      linux:
        events:
          process: true
          file: true
          network: true
        logging:
          file: info
fleet:
  kibana:
    protocol: https
    hosts:
      - f2e68108ba6f46219b2fe96b04cfbfb0.us-central1.gcp.foundit.no
```

8.0.0 Snapshot Kibana cloud details are:
```
BUILD 38728
COMMIT f2d961df6a5f78807dc2ef265aaba3c96d691881
Artifact link: https://snapshots.elastic.co/8.0.0-5823f363/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip
```

Also, let us know if anything else is required.

Thanks

**Comment by ph** [comment]
OK, looking at the output the fleet backend is doing the right thing and add the namespace, so I think the error is that endpoint doesn't honor that.

```yaml
  - id: 6493f0d0-7c52-40a2-b4c1-e0e5c57f38ad
    name: endpoint1
    revision: 1
    type: endpoint
    use_output: default
    meta:
      package:
        name: endpoint
        version: 0.17.0-dev.4
    data_stream:
      namespace: test_1
```

reassigning to @ferullo, is there a reason why endpoint do not honor that setting?

**Comment by ferullo** [comment]
Hmm.. Endpoint did have this bug but it was fixed. @dikshachauhan-qasource after enabling endpoint security and reproducing this issue can you share the file `c:\Program Files\Elastic\Endpoint\state\log\endpoint-000000.log` and share the output from `c:\Program Files\Elastic\Endpoint\elastic-endpoint.exe version`?

**Comment by dikshachauhan-qasource** [comment]
Hi @ferullo

Please find the `endpoint-000000.log file` in attachment. And elastic-endpoint.exe version is


```
 meta:
    package:
      name: endpoint
      version: 0.17.0-dev.4
  name: endpoint1

```

[endpoint-000000.log](https://github.com/elastic/beats/files/5677638/endpoint-000000.log)

Please let us know if anything else is required from our side.

**Comment by ferullo** [comment]
Thanks @dikshachauhan-qasource 

For future reference, that version is the version of the endpoint package in Kibana, not the Endpoint binary version.

I see in those logs that Endpoint is sending to the right indices. Are you sure the data you found in Kibana was sent by the currently installed Endpoint? Maybe it was from an Endpoint before you did this test or from a different Endpoint entirely..

**Comment by dikshachauhan-qasource** [comment]
Hi @ferullo

We have re-validated this issue on 8.0.0 Kibana snapshot Cloud build and found that issue is **still reproducible**. Build details are as follows:
```
BUILD 38781
COMMIT 0f408041b48a03fa46492f62d08fe5d8025390ea
Artifact link: https://snapshots.elastic.co/8.0.0-59591b4b/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip
```

**Observation:**
After installing agent, and on navigating to Discover tab 'default' is displayed at data_stream.namespace instead of instead of 'test_1' when 'event.dataset : "elastic_agent.endpoint_security" 'filter is applied at KQL query.
As per our understanding, 'test_1' as namespace should be displayed.

Also, when looked for namespace in endpoint logs, message displayed is 'not found in config'. Refer below:

```
{"@timestamp":"2020-12-15T09:25:51.3165732Z","agent":{"id":"b8e57b48-2869-bb55-3dea-e7193902ab22","type":"endpoint"},"ecs":{"version":"1.5.0"},"log":{"level":"notice","origin":{"file":{"line":91,"name":"Logging.cpp"}}},"message":"Logging.cpp:91 field (inputs[0].data_stream.namespace) not found in config","process":{"pid":7780,"thread":{"id":6444}}}
```

Required files to access are as follows:

View Policy : ['test1' agent policy.txt](https://github.com/elastic/beats/files/5695013/test1.agent.policy.txt)
Endpoint version: Version 0.17.0-dev.5
Endpoint log file: [endpoint-000000.log](https://github.com/elastic/beats/files/5695018/endpoint-000000.log)

Screenshot:
![#23020_Observation](https://user-images.githubusercontent.com/72375798/102201989-d152ca80-3eec-11eb-9738-0bceda026d99.jpg)

Please let us know if anything else is required.

**Comment by ferullo** [comment]
Oh, I missed before that you are filtering on `event.dataset : "elastic_agent.endpoint_security"`. Those documents are not sent by Elastic Endpoint. From the looks of what is in the screenshot of Discover, I think these are Endpoint logs being sent by Filebeat. 

@ph is Filebeat using the right namespace? It isn't in the integrations @dikshachauhan-qasource screenshotted so maybe it is still using the `default` namespace?

**Comment by ph** [comment]
:facepalm: you are correct these are endpoint security logs and they are assigned to default. I will lookup the behavior.

**Comment by EricDavisX** [comment]
ping to confirm intent on this... I don't recall the namespace discussion nuances but I know they exist.  Maybe this isn't a bug?  It might be good to write them out and get them doc'ed for us to reference publicly.

**Comment by ph** [comment]
@ruflin or @mostly Just to clarify the expected behavior, where do you expect a user to be able to configure to which namespace the logs and metric collected by the elastic agent for the running process should be, is hat a user configurable settings on the agent policy? How strongly we need this for GA?

**Comment by ruflin** [comment]
@ph Is there any reasons this should behave differently from other integrations? I think the namespace should be respected.

**Comment by ph** [comment]
I think this would be good for GA. This require some coordination from both side. Where would a user define the namespace user for a specific agent to send his metrics and log information? Right now the namespace is at the integration level not at agent level?

**Comment by ph** [comment]
@jen-huang What I mean, I think this require a dependency on Fleet to make it work, unless I am wrong.

**Comment by jen-huang** [comment]
@ph Ah, ok, I misunderstood a bit. Are these reported logs documents with `default` namespace "agent monitoring" logs? If so, maybe Fleet needs to send a user-configurable `namespace` as part of the monitoring yaml block?
```diff
agent:
  monitoring:
    enabled: true
+   namespace: test_1
    use_output: default
    logs: true
    metrics: true
```

**Comment by ph** [comment]
@jen-huang Yes, I believe what you are suggesting would work, I think the change is trivial, But it's more on your side where you want a user to configure this option?  Maybe this require a bit more thinking like I've set up the namespace a the agent policy settings level and by default everything use that namespace event for internal metrics and logging collection.

I think this issue is a bit convoluted, I am going to create a simple one with a better defined scope on our end.

**Comment by ph** [comment]
for everyone in this thread I've summarized the actual work in https://github.com/elastic/beats/issues/25350
