### ISSUE TITLE
[7.11 Snapshot] Agent goes to unhealthy state at Fleet UI after seemingly successful agent installation.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#23264]
**Kibana version:**
Kibana: 7.11 snapshot Kibana Cloud environment  

**Elasticsearch version:**
Elasticsearch: 7.11 snapshot Kibana Cloud environment  

**Host OS and Browser version:**
Windows 10, All

**Original install method (e.g. download page, yum, from source, etc.):**
7.11 snapshot Kibana Cloud environment  

[Ingest Manager]: Agent goes to unhealthy state at Fleet UI after seemingly successful agent installation.

**Preconditions**
1.  7.11 snapshot Kibana Cloud environment should be available.
```
BUILD 37480
COMMIT 876e859238cdc8ec487ca2608aacb1aa7faaa958
Artifact link: https://snapshots.elastic.co/7.11.0-683a2a3c/downloads/beats/elastic-agent/elastic-agent-7.11.0-SNAPSHOT-windows-x86_64.zip
```
2. Default policy having system integration should exist.[No change in namespace].

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to Fleet>Agents. Click on 'Create user and enable central management' button.
3. RDP to endpoint. Run installation command using default policy.
4. Navigate back to Fleet UI.
5. Observe, Agent shows up healthy and after few secs agent state changes to unhealthy.

Logs at UI:
```

11:39:01.738
elastic_agent
[elastic_agent][info] The Elastic Agent is currently in BETA and should not be used in production
11:39:01.747
elastic_agent
[elastic_agent][error] failed to load markeropen C:\Program Files\Elastic\Agent\data\.update-marker: The system cannot find the file specified.
11:39:03.859
elastic_agent
[elastic_agent][info] Detecting execution mode
11:39:03.859
elastic_agent
[elastic_agent][info] Agent is managed by Fleet
11:39:03.859
elastic_agent
[elastic_agent][info] EXPERIMENTAL - Inputs with variables are currently experimental and should not be used in production
11:39:03.859
elastic_agent
[elastic_agent][info] Docker provider skipped, unable to connect: protocol not available
11:39:03.860
elastic_agent
[elastic_agent][info] Starting stats endpoint
11:39:03.860
elastic_agent
[elastic_agent][info] Agent is starting
11:39:03.861
elastic_agent
[elastic_agent][info] Metrics endpoint listening on: \\.\pipe\elastic-agent (configured: npipe:///elastic-agent)
11:39:03.861
elastic_agent
[elastic_agent][warn] failed to ack update open C:\Program Files\Elastic\Agent\data\.update-marker: The system cannot find the file specified.
11:39:03.861
elastic_agent
[elastic_agent][info] New State ID is tcOZyjNu
11:39:03.861
elastic_agent
[elastic_agent][info] Converging state requires execution of 3 step(s)
11:39:03.862
elastic_agent
[elastic_agent][info] filebeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\filebeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
11:39:03.862
elastic_agent
[elastic_agent][info] filebeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\filebeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
11:39:03.862
elastic_agent
[elastic_agent][info] 2020-12-23T01:08:48-05:00: type: 'STATE': sub_type: 'STARTING' message: Application: filebeat--7.11.0-SNAPSHOT[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to STARTING: Starting
11:39:03.862
elastic_agent
[elastic_agent][info] metricbeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\metricbeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
11:39:03.863
elastic_agent
[elastic_agent][info] metricbeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\metricbeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
11:39:03.863
elastic_agent
[elastic_agent][info] 2020-12-23T01:08:50-05:00: type: 'STATE': sub_type: 'RUNNING' message: Application: filebeat--7.11.0-SNAPSHOT[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to RUNNING: Running
11:39:03.863
elastic_agent
[elastic_agent][info] 2020-12-23T01:08:59-05:00: type: 'STATE': sub_type: 'STARTING' message: Application: metricbeat--7.11.0-SNAPSHOT[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to STARTING: Starting
11:39:03.864
elastic_agent
[elastic_agent][info] filebeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\filebeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
11:39:03.864
elastic_agent
[elastic_agent][info] filebeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\filebeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
11:39:03.864
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for filebeat.7.11.0-SNAPSHOT
11:39:03.865
elastic_agent
[elastic_agent][info] 2020-12-23T01:09:00-05:00: type: 'STATE': sub_type: 'STARTING' message: Application: filebeat--7.11.0-SNAPSHOT--36643631373035623733363936343635[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to STARTING: Starting
11:39:03.865
elastic_agent
[elastic_agent][info] metricbeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\metricbeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
11:39:03.865
elastic_agent
[elastic_agent][info] metricbeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\metricbeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
11:39:03.865
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for metricbeat.7.11.0-SNAPSHOT
11:39:03.866
elastic_agent
[elastic_agent][info] 2020-12-23T01:09:01-05:00: type: 'STATE': sub_type: 'STARTING' message: Application: metricbeat--7.11.0-SNAPSHOT--36643631373035623733363936343635[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to STARTING: Starting
11:39:03.866
elastic_agent
[elastic_agent][info] Updating internal state
11:39:03.867
elastic_agent
[elastic_agent][info] 2020-12-23T01:09:01-05:00: type: 'STATE': sub_type: 'RUNNING' message: Application: metricbeat--7.11.0-SNAPSHOT[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to DEGRADED: 1 error: 1 error: Error creating runner from config: 1 error: metricset 'system/load' not found
11:39:03.867
elastic_agent
[elastic_agent][warn] Elastic Agent status changed to: 'degraded'
11:39:03.868
elastic_agent
[elastic_agent][info] 2020-12-23T01:09:02-05:00: type: 'STATE': sub_type: 'RUNNING' message: Application: filebeat--7.11.0-SNAPSHOT--36643631373035623733363936343635[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to RUNNING: Running
11:39:04.869
elastic_agent
[elastic_agent][info] 2020-12-23T01:09:03-05:00: type: 'STATE': sub_type: 'RUNNING' message: Application: metricbeat--7.11.0-SNAPSHOT--36643631373035623733363936343635[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to RUNNING: Running
12:28:33.763
elastic_agent
[elastic_agent][error] failed to load markeropen C:\Program Files\Elastic\Agent\data\.update-marker: The system cannot find the file specified.
12:28:33.780
elastic_agent
[elastic_agent][info] The Elastic Agent is currently in BETA and should not be used in production
12:28:35.127
elastic_agent
[elastic_agent][info] Detecting execution mode
12:28:35.127
elastic_agent
[elastic_agent][info] Agent is managed by Fleet
12:28:35.127
elastic_agent
[elastic_agent][info] EXPERIMENTAL - Inputs with variables are currently experimental and should not be used in production
12:28:35.128
elastic_agent
[elastic_agent][info] Docker provider skipped, unable to connect: protocol not available
12:28:35.129
elastic_agent
[elastic_agent][info] restoring current policy from disk
12:28:35.129
elastic_agent
[elastic_agent][info] New State ID is TgCvrNAC
12:28:35.129
elastic_agent
[elastic_agent][info] Converging state requires execution of 3 step(s)
12:28:35.130
elastic_agent
[elastic_agent][info] filebeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\filebeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
12:28:35.130
elastic_agent
[elastic_agent][info] filebeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\filebeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
12:28:35.130
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for filebeat.7.11.0-SNAPSHOT
12:28:35.131
elastic_agent
[elastic_agent][info] 2020-12-23T01:58:26-05:00: type: 'STATE': sub_type: 'STARTING' message: Application: filebeat--7.11.0-SNAPSHOT[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to STARTING: Starting
12:28:35.131
elastic_agent
[elastic_agent][info] metricbeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\metricbeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
12:28:35.131
elastic_agent
[elastic_agent][info] metricbeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\metricbeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
12:28:35.132
elastic_agent
[elastic_agent][info] Updating internal state
12:28:35.132
elastic_agent
[elastic_agent][info] New State ID is TgCvrNAC
12:28:35.132
elastic_agent
[elastic_agent][info] Converging state requires execution of 2 step(s)
12:28:35.132
elastic_agent
[elastic_agent][info] filebeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\filebeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
12:28:35.132
elastic_agent
[elastic_agent][info] filebeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\filebeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
12:28:35.132
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for filebeat.7.11.0-SNAPSHOT
12:28:35.132
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for metricbeat.7.11.0-SNAPSHOT
12:28:35.132
elastic_agent
[elastic_agent][info] 2020-12-23T01:58:27-05:00: type: 'STATE': sub_type: 'STARTING' message: Application: metricbeat--7.11.0-SNAPSHOT[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to STARTING: Starting
12:28:35.132
elastic_agent
[elastic_agent][info] filebeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\filebeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
12:28:35.132
elastic_agent
[elastic_agent][info] filebeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\filebeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
12:28:35.132
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for filebeat.7.11.0-SNAPSHOT
12:28:35.132
elastic_agent
[elastic_agent][info] 2020-12-23T01:58:28-05:00: type: 'STATE': sub_type: 'STARTING' message: Application: filebeat--7.11.0-SNAPSHOT--36643631373035623733363936343635[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to STARTING: Starting
12:28:35.132
elastic_agent
[elastic_agent][info] metricbeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\metricbeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
12:28:35.132
elastic_agent
[elastic_agent][info] metricbeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\metricbeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
12:28:35.132
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for metricbeat.7.11.0-SNAPSHOT
12:28:35.132
elastic_agent
[elastic_agent][info] 2020-12-23T01:58:29-05:00: type: 'STATE': sub_type: 'STARTING' message: Application: metricbeat--7.11.0-SNAPSHOT--36643631373035623733363936343635[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to STARTING: Starting
12:28:35.143
elastic_agent
[elastic_agent][info] operation 'operation-start' skipped for filebeat.7.11.0-SNAPSHOT
12:28:35.143
elastic_agent
[elastic_agent][info] metricbeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\metricbeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
12:28:35.147
elastic_agent
[elastic_agent][info] metricbeat.7.11.0-SNAPSHOT already exists in C:\Program Files\Elastic\Agent\data\elastic-agent-e1e0c1\downloads\metricbeat-7.11.0-SNAPSHOT-windows-x86_64.zip. Skipping operation operation-fetch
12:28:35.148
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for metricbeat.7.11.0-SNAPSHOT
12:28:35.148
elastic_agent
[elastic_agent][info] operation 'operation-start' skipped for metricbeat.7.11.0-SNAPSHOT
12:28:35.148
elastic_agent
[elastic_agent][info] Updating internal state
12:28:35.149
elastic_agent
[elastic_agent][info] Starting stats endpoint
12:28:35.149
elastic_agent
[elastic_agent][info] Agent is starting
12:28:35.150
elastic_agent
[elastic_agent][warn] failed to ack update open C:\Program Files\Elastic\Agent\data\.update-marker: The system cannot find the file specified.
12:28:35.150
elastic_agent
[elastic_agent][info] Metrics endpoint listening on: \\.\pipe\elastic-agent (configured: npipe:///elastic-agent)
12:28:35.151
elastic_agent
[elastic_agent][info] 2020-12-23T01:58:33-05:00: type: 'STATE': sub_type: 'RUNNING' message: Application: filebeat--7.11.0-SNAPSHOT[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to RUNNING: Running
12:28:35.151
elastic_agent
[elastic_agent][info] 2020-12-23T01:58:33-05:00: type: 'STATE': sub_type: 'RUNNING' message: Application: filebeat--7.11.0-SNAPSHOT--36643631373035623733363936343635[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to RUNNING: Running
12:28:42.155
elastic_agent
[elastic_agent][info] 2020-12-23T01:58:40-05:00: type: 'STATE': sub_type: 'RUNNING' message: Application: metricbeat--7.11.0-SNAPSHOT--36643631373035623733363936343635[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to RUNNING: Running
12:28:42.157
elastic_agent
[elastic_agent][info] 2020-12-23T01:58:40-05:00: type: 'STATE': sub_type: 'RUNNING' message: Application: metricbeat--7.11.0-SNAPSHOT[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to DEGRADED: 1 error: 1 error: Error creating runner from config: 1 error: metricset 'system/load' not found
12:28:42.157
elastic_agent
[elastic_agent][warn] Elastic Agent status changed to: 'degraded'
```

**Reference ticket Id:**
N/A

**Actual Result**
Agent goes to unhealthy state at Fleet UI after seemingly successful agent installation.

**Expected Result**
Agent goes should remain healthy state at Fleet UI after seemingly successful agent installation.

**What's working**
N/A

**What's not working**
Agent goes to unhealthy state when using endpoint security as well in default policy.

**Screenshots:** 
![Agentunhealthy](https://user-images.githubusercontent.com/72375798/102972438-109e9e00-4521-11eb-96f7-126329cca9ac.jpg)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
I thought we had this logged separately already, I am not on line to find the duplicate tho...

Anyhow, this seems severe and we should follow up.

**Comment by michalpristas** [comment]
this will be related to the log right above the agent going to degraded state
```
[elastic_agent][info] 2020-12-23T01:58:40-05:00: type: 'STATE': sub_type: 'RUNNING' message: Application: metricbeat--7.11.0-SNAPSHOT[43ba3b50-44e5-11eb-8c9c-b5f5619d3c4c]: State changed to DEGRADED: 1 error: 1 error: 
Error creating runner from config: 1 error: metricset 'system/load' not found
```

when application status changes overall agent status changes.  
we should take a look why this is reporting this way, `system/load` should not be available on windows thus it should not fail with error.

**Comment by michalpristas** [comment]
looking at it and thinking about possible solutions, this should not be handled at the agent level.
even though it manifests as agent being unhealthy, but it is because agent does the right thing and takes reported application status into account. 

@ruflin should we update system package to have a condition saying `generate system/load if OS!=windows' maybe?
or should it be handled at the metricbeat level as metricbeat should be aware of its requirements and not even try to create runner for something which is unsupported.

**Comment by ph** [comment]
@michalpristas @fearful-symmetry should know about this about this, I believe he added platform condition on some of the input.

**Comment by EricDavisX** [comment]
Alex's work for dynamic input usage in integration was merged for Windows / System Integration here: https://github.com/elastic/integrations/pull/411 - I'd have to research package promotion and roll out to know if we expect it in use in our 7.11 BC (or snapshot) systems.

**Comment by fearful-symmetry** [comment]
@ph @michalpristas I fixed a related issue here: https://github.com/elastic/integrations/pull/498

@michalpristas what OS is that? Right now we have a conditional to block `load` running on windows, but if some other component of fleet is still trying to start it on Windows, I'm not sure what the fix would be.

**Comment by michalpristas** [comment]
@fearful-symmetry this issue is related to Win 10 with 7.11 kibana
was this a recent change, something which might be not present at the deployment mentioned above?

**Comment by fearful-symmetry** [comment]
@michalpristas system is currently on `0.10.5`.

It appears you're using a relatively old version that's probably broken:

```
          name: system
          version: "0.9.1"
```

**Comment by michalpristas** [comment]
using cloud instance, so if this seems old then somethings wrong there. 
do you know how pairing/dependency is defined?

**Comment by EricDavisX** [comment]
we're following up on getting the newer System package deployed to prod so we can verify that ^ directly above issue goes away. I'm still seeing problems with BC2 of 7.11 so I'm putting a new ticket in.

**Comment by EricDavisX** [comment]
we logged a new issue with clearer status an repro steps from 7.11 BC2 (which shows different symptoms and behavior as this) so I'm closing it as fixed.

follow https://github.com/elastic/beats/issues/23402  for more details.  in 7.11 BC2 macOS and Linux seem ok.  only windows problems are confirmed, as of now.  just fyi
