### ISSUE TITLE
[Ingest Manager]: Agent stays in 'Updating' state on 7.12.0 https://staging.found.no/login build

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/beats#24150]
**Description**
Agent stays in 'Updating' state on 7.12.0 build

**Build Details:**
```
Version: 7.12.0 BC1
Build: 38938
Commit: 038fd51b0474c96e4d3ae58db1308c5f8aba71bd
```
Artifacts: [BC1](https://staging.elastic.co/7.12.0-8486f7d1/summary-7.12.0.html)

**Browser Details:**
All

**Preconditions:**
1. 7.12.0 Environment should exist.
2. Policy and artifacts should exist

**Steps to Reproduce:**
1. Login to the Kibana environment.
2. Go to Add Agents fly out.
3. Copy installation command for windows Agent.
4. RDP to the endpoint. Open Power Shell with Admin mode.
5. Run command copied at step 3 at location c:>Program Files>elastic-agent
6. Observe that agent is displaying as "Updating".

**Note:**
- **Issue also occurring with both the Windows Signing State [OFF and ON]**
- **Issue also occurring on agent installation with added parameter: --staging <agent_hash>.**

**Impacted Test case:**
N/A

**Actual Result:**
Agent stays in 'Updating' state on 7.12.0 build

**Expected Result:**
Agent should be in 'Healthy' state after successful installation on 7.12.0 build and endpoint security added under policy should be installed.

**What's working:**
- **Standalone agents are working fine**
![standalone](https://user-images.githubusercontent.com/61860752/108685770-8f608900-751a-11eb-94bb-afe0b95231f7.JPG)

**What's not working:**
This issue is also occurring on Mac and Linux.

**Screenshot:**
![agent](https://user-images.githubusercontent.com/61860752/108678881-b36b9c80-7511-11eb-966b-10c2c22f7eea.jpg)

![Install_agent](https://user-images.githubusercontent.com/61860752/108678809-9afb8200-7511-11eb-8d07-9de6a5c5f832.jpg)

**Logs**
- Elastic-agent logs
[logs.zip](https://github.com/elastic/beats/files/6020642/logs.zip)

**Comment by deepikakeshav-qasource** [comment]
@manishgupta-qasource Please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by EricDavisX** [comment]
@ph do you want us to add a step to our usual triage process where we remove 'System' Integration from the equation to confirm if it will relate to the inputs in that Integration?

I see this line repeated periodically in logs:
{"log.level":"error","@timestamp":"2021-02-22T14:07:49.888+0530","log.origin":{"file.name":"application/emitter.go","file.line":107},"message":"Failed to render configuration with latest context from composable controller: fail to extract program configuration: invalid configuration missing outputs configuration","ecs.version":"1.6.0"}
 
It sounds possibly related to the config, 7.12 bc1 on cloud prod is showing with System Integration 0.10.7
currently.  I know there is a 0.10.8 (and .9) we were considering to ship, unsure if those coming changes relate to this or not.

Policy citation does mention 'Endpoint' so we can include that as part of the repro considerations, which is on package version 0.17.1.

**Comment by EricDavisX** [comment]
Update:  i reproduced this on my macOS host Catalina with 7.12.0 BC1 candidate without Endpoint included in policy, just with full defaults as Fleet installs.

**Comment by ph** [comment]
OK, looking at error referenced in your comments it's seems "outputs" is missing, @michalpristas @nchaulet I am not sure if the issues described here is a side effect of the migration to Fleet-Server?

**Comment by michalpristas** [comment]
copying from slack
may be related to https://github.com/elastic/beats/commit/c0c771e50e012a7de7bbe8f5923374615da27ab2

let’s check if logs on machine says agent is managed by fleet. if not. this ^^ is fixing it.

it kinda matches with commit history, enroll was pushed 15th, bc1 is 18 and fix is 19th

**Comment by michalpristas** [comment]
i see this is not related, but looks like the other issue we were having, i will check backports

**Comment by michalpristas** [comment]
this line says
```

{"log.level":"info","@timestamp":"2021-02-22T12:27:45.238+0530","log.origin":{"file.name":"application/application.go","file.line":74},"message":"Agent is managed locally","ecs.version":"1.6.0"}
```
that agent is managed lcoally, after restartit will connect to fleet. 
the recurring output error which seems to occure every feconfw iguratio n seemslike a bug but not related to unhealthy state. 

agent is unhealthy because it starts in standalone and never checks in so never change status from the one initiated during enrolling process. The fix mentioned above is actually a fix for this issue

**Comment by EricDavisX** [comment]
This is believed fixed in the latest snapshot and will be picked up in BC2 we think.  There is however a different issue that seems Windows specific in latest 7.12 - https://github.com/elastic/beats/issues/24180 please track that if you need a working Windows Agent, we are trying to identify root cause.

**Comment by ferullo** [comment]
FWIW I hit this issue and "solved" it by rebooting the host. I know this isn't a true solution but it might help unblock some testing.

**Comment by deepikakeshav-qasource** [comment]
Hi,

We have validated this ticket on **7.12.0 BC1** on production build and **7.12.0 BC2** on staging. Please find the below observations:

**Observation 1:**
- **7.12.0 BC1 on production:**

**Build Details:**
```
Version: 7.12.0 BC1
Build: 38938
Commit: 038fd51b0474c96e4d3ae58db1308c5f8aba71bd
Artifacts: https://staging.elastic.co/7.12.0-8486f7d1/summary-7.12.0.html
```
**Steps:**
1. Install the agent.
2. Agent goes to updating status.
3. Reboot the endpoint.
4. Agent goes to healthy status

**Screenshot:**
![7 12 0_BC1](https://user-images.githubusercontent.com/61860752/108955266-e2118080-7693-11eb-8d90-d2d54aa364b3.jpg)

**Observation 2:**
- **7.12.0 BC2 on Staging:**

**Build Details:**
```
Platform: Staging
Version: 7.12.0 BC2
Build: 39000
Commit: 4f65a5a1268fa78f1af9117d12312e1cee433376
Artifacts: https://staging.elastic.co/7.12.0-37f40745/summary-7.12.0.html
```

**Steps:**
1. Install the agent.
2. Agent goes to unhealthy status.
3. Reboot the endpoint.
4. Agent still in an unhealthy state.

**Screenshot**
![1](https://user-images.githubusercontent.com/61860752/108955270-e342ad80-7693-11eb-9561-7994ffce042f.JPG)
![2](https://user-images.githubusercontent.com/61860752/108955273-e50c7100-7693-11eb-8f43-465adb7e7d26.JPG)
![3](https://user-images.githubusercontent.com/61860752/108955278-e63d9e00-7693-11eb-87ff-cb20bf4ecb67.JPG)

**Logs**
[logs.zip](https://github.com/elastic/beats/files/6033710/logs.zip)

**Note:** For Mac and Linux agent is in a healthy state on **7.11.0 BC2** staging

**Screenshot for Mac**
![Mac_bc2](https://user-images.githubusercontent.com/61860752/108958793-7f22e800-7699-11eb-92cf-dd2d3ad84d42.jpg)

**Screenshot for Linux**
![Linux](https://user-images.githubusercontent.com/61860752/108958799-80ecab80-7699-11eb-8869-e401adadac6e.JPG)

Please let us know if we are missing anything.

Thanks!!

**Comment by ph** [comment]
I have assigned it to you @michalpristas and added it to the board.

**Comment by dikshachauhan-qasource** [comment]
Hi @michalpristas cc @EricDavisX 

We are still facing issues with Windows agent on 7.12 staging cloud build. Below are our observations:

- Agent comes to Healthy state after installation. However, metricbeat service still not starting by itself.
- Filebeat is running.

**Screenshot for Agent logs page and datastreams:**
![image](https://user-images.githubusercontent.com/72375798/109463507-1ff31800-7a8b-11eb-867f-481c90742b30.png)

**Attempted for work-around:** 
- Replaced content of `C:\Program Files\Elastic\Agent\data\elastic-agent-54c058\install\metricbeat-7.12.0-windows-x86_6` with `C:\Program Files\Elastic\Agent\data\elastic-agent-54c058\downloads\metricbeat-7.12.0-windows-x86_64`

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/109464109-21711000-7a8c-11eb-941d-bf05989b3b64.png)

**Build details:**\
```
BUILD 39000
COMMIT 4f65a5a1268fa78f1af9117d12312e1cee433376
Artifact link: https://staging.elastic.co/7.12.0-37f40745/summary-7.12.0.html
```

@EricDavisX , As fixes are not available and feature is working by work-around. So we are not marking testcases for Windows agent and waiting for the fixes. Once fixes are available we will resume testing through windows agent.

Thanks
QAS

**Comment by EricDavisX** [comment]
what you repot above sounds like the known problem tracked in https://github.com/elastic/beats/issues/24180
 - but all the logs and info is helpful.  I sent info via email / slack about testing the above issue's PR to see if it works.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX ,

Yes, issue addressed in above comment was just posted for agent current behavior on 7.12 BC build as we are continuing testing on BC build.
Further, Issue reported at  #24180 was on 7.12 Snapshot build. Also as per the current updates, we will update our observations on same ticket after validating fixes on 8.0.

Thanks
QAS

**Comment by michalpristas** [comment]
fix for metricbeat ongoing here: https://github.com/elastic/beats/pull/24253

**Comment by michalpristas** [comment]
can we verify this got fixed by fix above?

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource @amolnater-qasource hi, can you help @deepikakeshav-qasource test it out on BC3?  Thanks

**Comment by deepikakeshav-qasource** [comment]
Hi @EricDavisX

We have validated this ticket on 7.12.0 BC4 On-Prem build and observed that issue is **Fixed**. Agent is displaying in "Healthy" state on Windows OS.

**Build Details:**
```
Version: 7.12.0-BC4
Platform: On-Prem
Commit:99ac38d70e426f589bb61a034c96e602d759cfab
Build:39242
https://staging.elastic.co/7.12.0-336ff10d/summary-7.12.0.html
```

**Screenshot:**
![Agent](https://user-images.githubusercontent.com/61860752/110628152-c8f6ec80-81c8-11eb-8557-90a59e0e3f1f.jpg)

**Logs**
[elastic-agent-json.log](https://github.com/elastic/beats/files/6115984/elastic-agent-json.log)

Hence, We are closing this ticket.

Thanks!!
