### ISSUE TITLE
`filestream` input logs an error when an existing input is reloaded with the same ID

### ISSUE THREAD

**Issue by kvch** [elastic/beats#31767]
When loading inputs from external files is enabled and there is only one `filestream` input enabled the following error is returned after the first reload:

```
filestream input with ID 'my-unique-id' already exists, this will lead to data duplication, please use a different ID
```

The problem is that the input ID stays in the bookeeper of the input manager. On reload we should remove all IDs from the manager, so the check does not interfere with previous configurations.

### Example configuration

`filebeat.yml`
```yaml
 filebeat.config.inputs:
   enabled: true
   path: inputs.d/*.yml

 output.file:
   enabled: true
```
`inputs.d/my-input.yml`
```yaml
- type: filestream
  id: my-unique-id
  paths: [/var/log/messages]
```

There is no workaround. At the moment it is not possible to configure `filestream` input from external configuration files.

Reported on discuss: https://discuss.elastic.co/t/filebeat-raise-error-filestream-input-id-already-exist

CC @belimawr

**Comment by belimawr** [comment]
That is fixed by: https://github.com/elastic/beats/pull/32309

**Comment by andreycha** [comment]
I see that the fix has been backported to 7.17. Are there plans already for the next release date?

**Comment by cmacknz** [comment]
There is a planned 7.17.6 release in the near future.

**Comment by abraxxa** [comment]
According to the release notes, the fix is included in 7.17.6 but I still see the error happening with a single filestream input in a file in the inputs.d directory.

**Comment by belimawr** [comment]
> According to the release notes, the fix is included in 7.17.6 but I still see the error happening with a single filestream input in a file in the inputs.d directory.

Hi @abraxxa, could you share some more details about how you're experiencing this issue? A minimal config and steps to reproduce would be ideal.

I've just checked the `v7.17.6` tag and the fix is there. If you can help me to reproduce it, I'll investigate it further.

**Comment by abraxxa** [comment]
Hi @belimawr, thanks for your response!

Exactly as reported above.

I've started yesterday changing `type: log` to `filestream` and it happened on the very first server where I only have a single file in the input.d directory which collects logs from three files (no globs involved).
Filebeat is version 7.17.6 and the VM runs on Debian 10.

**Comment by belimawr** [comment]
Sorry if I'm asking something obvious, but are you sure you didn't have any filestream input configured on your `filebeat.yml`?

Did you touch/edit the file(s) on `inputs.d/`?

I'm just trying to understand what triggered it. Starting a Filebeat with a single filestream input on `inputs.d` without any other filestream configured on `filebeat.yml` should never trigger this message.

**Comment by abraxxa** [comment]
filebeat.yml is untouched from the deb package. It has one disabled input of `type: filestream` for `/var/log/*.log`.
But as the error message included the id I assigned to the filestream input in the input.d directory, I didn't check it before.

That's the exact error message:
`Sep 05 17:40:16 tsa-tc-dot1x-3 filebeat[23435]: 2022-09-05T17:40:16.552+0200        ERROR        [input]        input-logfile/manager.go:183        filestream input with ID 'dot1x-services' already exists, this will lead to data duplication, please use a different ID`

And here is the file in the input.d directory:

```
---
- type: filestream
  id: dot1x-services
  paths:
      - /var/log/radiator-dot1x/central-logging-radiator.json
      - /var/log/radiator-dot1x/central-logging-authentication.json
      - /var/log/radiator-dot1x/central-logging-accounting.json
  encoding: utf-8
  parsers:
      - ndjson:
          keys_under_root: true
          overwrite_keys: true
          expand_keys: true
  prospector.scanner.check_interval: 1s
  processors:
    - add_fields:
        target: "data_stream"
        fields:
            dataset: "radiator"
            type: "logs"
    - add_fields:
        target: "event"
        fields:
            module: "radiator-dot1x"
```

**Comment by belimawr** [comment]
Thanks! I'll investigate it.

**Comment by belimawr** [comment]
Ok, I can confirm that this is still happening on `v7.16.6` as well as on `main.

**Comment by abraxxa** [comment]
Great, thanks!
One more info: it happened when first restarting filebeat with the input converted from log to filestream as well as on reload and restart now.

**Comment by belimawr** [comment]
yes, for some reason Filebeat is reading the config twice on startup, I believe it reads the `inputs.d` as the normal startup sequence, then starts watching `inputs.d` which trigger a re-read of the files, hence a loading again the same filestream input. But it does not stop the current one before starting the new one.

**Comment by belimawr** [comment]
# The problem
I believe I got to the root cause:
- The normal startup process loads all inputs, including the ones on `inputs.d`
- Because things happens concurrently, the input is loaded (it's ID is added to the inputManager's map), but the harvester is not started yet.
- The inputReloader is started in another goroutine
- The inputReloaders reads again `inputs.d` and starts the inputs there.
- Because the harvester has not started yet (and the other things that lead to the harvester running), the inputRelaoder does not know it needs to stop an input, so it only starts (again) the filestream input

# Why does it not lead to two inputs running at the same time?
Well, the harvester is smart enough not to run two harvesters for the same file from the same input. So only one of the inputs actually run. This leads to no issues while running Filebeat.

# Workaround
Unfortunately the easiest workaround is to add the input configuration directly to `filebeat.yml` and not use `inputs.d`

**Comment by belimawr** [comment]
# Some extra information
Here are the stacktraces of when the filestream input is first loaded by the input manager and the second time it's loaded by the input manager (via the reloader), which triggers the log message:

## First time, it comes from the "normal" startup that started on `main.go`
```
(dlv) bt
 0  0x00000000028c3bc0 in github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*InputManager).Create
    at ./input/filestream/internal/input-logfile/manager.go:162
 1  0x00000000028aed86 in github.com/elastic/beats/v7/filebeat/input/v2.(*Loader).Configure
    at ./input/v2/loader.go:110
 2  0x00000000028afda5 in github.com/elastic/beats/v7/filebeat/input/v2/compat.(*factory).CheckConfig
    at ./input/v2/compat/compat.go:73
 3  0x00000000028b0927 in github.com/elastic/beats/v7/filebeat/input/v2/compat.composeFactory.CheckConfig
    at ./input/v2/compat/composed.go:48
 4  0x00000000028b0c25 in github.com/elastic/beats/v7/filebeat/input/v2/compat.(*composeFactory).CheckConfig
    at <autogenerated>:1
 5  0x000000000281fcc2 in github.com/elastic/beats/v7/filebeat/channel.(*onCreateFactory).CheckConfig
    at ./channel/runner.go:64
 6  0x00000000016dc967 in github.com/elastic/beats/v7/libbeat/cfgfile.(*Reloader).Check
    at /home/tiago/devel/beats/libbeat/cfgfile/reload.go:155
 7  0x00000000028b6655 in github.com/elastic/beats/v7/filebeat/beater.(*crawler).Start
    at ./beater/crawler.go:83
 8  0x00000000028b9431 in github.com/elastic/beats/v7/filebeat/beater.(*Filebeat).Run
    at ./beater/filebeat.go:338
 9  0x00000000027fb7d3 in github.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).launch
    at /home/tiago/devel/beats/libbeat/cmd/instance/beat.go:475
10  0x00000000027f9c05 in github.com/elastic/beats/v7/libbeat/cmd/instance.Run.func1
    at /home/tiago/devel/beats/libbeat/cmd/instance/beat.go:180
11  0x00000000027f9a85 in github.com/elastic/beats/v7/libbeat/cmd/instance.Run
    at /home/tiago/devel/beats/libbeat/cmd/instance/beat.go:181
12  0x000000000280af58 in github.com/elastic/beats/v7/libbeat/cmd.genRunCmd.func1
    at /home/tiago/devel/beats/libbeat/cmd/run.go:36
13  0x00000000011a52c3 in github.com/spf13/cobra.(*Command).execute
    at /home/tiago/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860
14  0x00000000011a59dd in github.com/spf13/cobra.(*Command).ExecuteC
    at /home/tiago/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974
Sending output to pager...
 0  0x00000000028c3bc0 in github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*InputManager).Create
    at ./input/filestream/internal/input-logfile/manager.go:162
 1  0x00000000028aed86 in github.com/elastic/beats/v7/filebeat/input/v2.(*Loader).Configure
    at ./input/v2/loader.go:110
 2  0x00000000028afda5 in github.com/elastic/beats/v7/filebeat/input/v2/compat.(*factory).CheckConfig
    at ./input/v2/compat/compat.go:73
 3  0x00000000028b0927 in github.com/elastic/beats/v7/filebeat/input/v2/compat.composeFactory.CheckConfig
    at ./input/v2/compat/composed.go:48
 4  0x00000000028b0c25 in github.com/elastic/beats/v7/filebeat/input/v2/compat.(*composeFactory).CheckConfig
    at <autogenerated>:1
 5  0x000000000281fcc2 in github.com/elastic/beats/v7/filebeat/channel.(*onCreateFactory).CheckConfig
    at ./channel/runner.go:64
 6  0x00000000016dc967 in github.com/elastic/beats/v7/libbeat/cfgfile.(*Reloader).Check
    at /home/tiago/devel/beats/libbeat/cfgfile/reload.go:155
 7  0x00000000028b6655 in github.com/elastic/beats/v7/filebeat/beater.(*crawler).Start
    at ./beater/crawler.go:83
 8  0x00000000028b9431 in github.com/elastic/beats/v7/filebeat/beater.(*Filebeat).Run
    at ./beater/filebeat.go:338
 9  0x00000000027fb7d3 in github.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).launch
    at /home/tiago/devel/beats/libbeat/cmd/instance/beat.go:475
10  0x00000000027f9c05 in github.com/elastic/beats/v7/libbeat/cmd/instance.Run.func1
    at /home/tiago/devel/beats/libbeat/cmd/instance/beat.go:180
11  0x00000000027f9a85 in github.com/elastic/beats/v7/libbeat/cmd/instance.Run
    at /home/tiago/devel/beats/libbeat/cmd/instance/beat.go:181
12  0x000000000280af58 in github.com/elastic/beats/v7/libbeat/cmd.genRunCmd.func1
    at /home/tiago/devel/beats/libbeat/cmd/run.go:36
13  0x00000000011a52c3 in github.com/spf13/cobra.(*Command).execute
    at /home/tiago/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860
14  0x00000000011a59dd in github.com/spf13/cobra.(*Command).ExecuteC
    at /home/tiago/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974
15  0x00000000028e13c6 in github.com/spf13/cobra.(*Command).Execute
15  0x00000000028e13c6 in github.com/spf13/cobra.(*Command).Execute
    at /home/tiago/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
16  0x00000000028e13c6 in main.main
    at ./main.go:36
17  0x0000000000ff5db2 in runtime.main
    at /usr/local/go/src/runtime/proc.go:250
18  0x0000000001028d81 in runtime.goexit
    at /usr/local/go/src/runtime/asm_amd64.s:1594
```

## Second time, the harvester is not running, but the input manager already has got the ID registered. It runs on a different goroutine
```
(dlv) bt
 0  0x00000000028c3bc0 in github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*InputManager).Create
    at ./input/filestream/internal/input-logfile/manager.go:162
 1  0x00000000028aed86 in github.com/elastic/beats/v7/filebeat/input/v2.(*Loader).Configure
    at ./input/v2/loader.go:110
 2  0x00000000028afe5a in github.com/elastic/beats/v7/filebeat/input/v2/compat.(*factory).Create
    at ./input/v2/compat/compat.go:84
 3  0x00000000028b0a22 in github.com/elastic/beats/v7/filebeat/input/v2/compat.composeFactory.Create
    at ./input/v2/compat/composed.go:62
 4  0x00000000028b0cd5 in github.com/elastic/beats/v7/filebeat/input/v2/compat.(*composeFactory).Create
    at <autogenerated>:1
 5  0x000000000281ffa9 in github.com/elastic/beats/v7/filebeat/channel.RunnerFactoryWithCommonInputSettings.func1
    at ./channel/runner.go:99
 6  0x000000000281fd3e in github.com/elastic/beats/v7/filebeat/channel.(*onCreateFactory).Create
    at ./channel/runner.go:68
 7  0x00000000016dc418 in github.com/elastic/beats/v7/libbeat/cfgfile.createRunner
    at /home/tiago/devel/beats/libbeat/cfgfile/list.go:188
 8  0x00000000016db15f in github.com/elastic/beats/v7/libbeat/cfgfile.(*RunnerList).Reload
    at /home/tiago/devel/beats/libbeat/cfgfile/list.go:103
 9  0x00000000016dcd35 in github.com/elastic/beats/v7/libbeat/cfgfile.(*Reloader).Run
    at /home/tiago/devel/beats/libbeat/cfgfile/reload.go:215
10  0x00000000028b6949 in github.com/elastic/beats/v7/filebeat/beater.(*crawler).Start.func1
    at ./beater/crawler.go:97
11  0x0000000001028d81 in runtime.goexit
    at /usr/local/go/src/runtime/asm_amd64.s:1594
(dlv) 
```

**Comment by belimawr** [comment]
@pierrehilbert @cmacknz we should look into the priority of this, when using the `inputs.d` it emits misleading errors about duplicated filestream IDs. Aside that, it seems to have no effect onto Filebeat's execution.

**Comment by abraxxa** [comment]
Thanks for debugging this so quickly! 👍🏻 

Can `inputReloader` be disabled?

**Comment by belimawr** [comment]
> Can `inputReloader` be disabled?

Yes, you can add:
```
filebeat.config:
  inputs:
    enabled: false
    path: inputs.d/*.yml
```
on your `filebeat.yml`

This option is enabled by default, hence it's not explicitly listed on `filebeat.yml` (`/etc/filebeat/filebeat.yml` on the deb package)

Or just not add anything into `inputs.d` folder and keep all your inputs into `filebeat.yml`

**Comment by abraxxa** [comment]
But then the file in the inputs.d directory won't be loaded.
My goal was to load it but not discover any changes to it as I handle deployment and restarting/reloading with Ansible.

**Comment by belimawr** [comment]
yes, that's the downside of the workaround, you'd have to add all input configuration to `filebeat.yml`.

You can add your input configurations on any part of `filebeat.yml`, so you could add it at the very end, e.g:

```yml
filebeat.config.inputs:
  enabled: false
  path: inputs.d/*.yml
  reload.period: 60s

output.file:
  enabled: true
  path: "/tmp/filebeat-out"
  
filebeat.inputs:
  - type: filestream
    id: my-unique-id
    paths: [/tmp/flog.log]
```

That might make it a bit easier to manipulatethis file with Ansible  (e.g: concatenate a default config file with the input configuration) . If you don't need to watch the `inputs.d` directory for changes, that might be an option for you.

**Comment by abraxxa** [comment]
I just read up on this feature in the docs. What if I disable the input.d file reloading using `reload.enabled: false`?

**Comment by belimawr** [comment]
> I just read up on this feature in the docs. What if I disable the input.d file reloading using `reload.enabled: false`? Sadly the docs don't include its default value.

I did a quick test here and it woks :D. I'll update my other comment with the workaround.

I totally missed that option :man_facepalming: . Thanks for finding it!

**Comment by abraxxa** [comment]
For me it doesn't fix the issue, even when starting filebeat the error is logged.

**Comment by belimawr** [comment]
Indeed it's still happening :/

I've just tested it again and it still happening. Maybe I got lucky with the order the goroutines were running the first time I tested it.

Well, the best solution seem to be to just avoid using the `inputs.d` directory.

**Comment by abraxxa** [comment]
Solution or workaround?

**Comment by belimawr** [comment]
> Solution or workaround?

workaround.

**Comment by abraxxa** [comment]
Can you please give me an update on this issue? Thanks!

**Comment by belimawr** [comment]
> Can you please give me an update on this issue? Thanks!

At the moment I have no updates to give :/

**Comment by abraxxa** [comment]
Can I do something to raise the priority? We have a support contract.

**Comment by belimawr** [comment]
> Can I do something to raise the priority? We have a support contract.

Yes, if you have a support contract, please reach out to support and mention this GitHub issue.

**Comment by fixed77** [comment]
version 7.17.8, the problem is still relevant

**Comment by rafi0101** [comment]
version 8.5.2, this problem is still relevant. Any news?

**Comment by MatthiasLenhardt** [comment]
We faced the problem, too.
My workaround was to move back to deprecated input type "log", because multiple config files are very convenient for us.
Any news?

**Comment by tanvp112** [comment]
The issue exist with version 8.6.1

**Comment by pierrehilbert** [comment]
Is the solution here only to clear the Input Manager bookkeeper first when we are reloading?

**Comment by belimawr** [comment]
It seems to be related with some race conditions when reloading inputs. There are quire a lot asynchronous things happening when inputs are started/stopped.

**Comment by anthonynguyen394** [comment]
I am facing this problem even if I am not using external input. I can confirm that I am facing data duplication as well. I am using version 8.6.2 of Filebeat, my config: 

`
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: file
spec:
  type: filebeat
  version: 8.6.2
  config:
    logging.metrics.enabled: false
    filebeat:
      autodiscover:
        providers:
          - type: kubernetes
            templates:
              - condition:
                  and: 
                    - regexp:
                        kubernetes.namespace: "^<namespace>-*"
                    - not:
                        regexp:
                          kubernetes.pod.name: "^<pod name>-*"
                config:
                  - type: filestream
                    id: core-container-logs
                    paths:
                      - /var/log/containers/*-${data.kubernetes.container.id}.log
                    parsers:
                      - multiline:
                          type: pattern
                          # Match date pattern of 2023:03:16:13:23:49 at beginning of each log line
                          pattern: '^[0-9]{4}:[0-9]{2}:[0-9]{2}:[0-9]{2}:[0-9]{2}:[0-9]{2}'
                          negate: true
                          match: after
    processors:
      - drop_fields:
          fields: 
            - "/kubernetes.node.labels.*/"
            - "/kubernetes.namespace_labels.*/"
            - "/kubernetes.labels.*/"
            - "/agent.*/"
            - "/host.*/"
            - "/input.*/"
            - "/ecs.*/"
            - "/kubernetes.namespace_uid.*/"
            - "/kubernetes.node.uid.*/"
            - "/container.runtime.*/"
            - "/log.offset.*/"
            - "/stream.*/"
          ignore_missing: true
    output.logstash:
      hosts: ["logstash.elastic-system.svc:5044"]
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        tolerations:
        - key: dedicated
          operator: Exists
          effect: NoSchedule       
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          - name: jsonlogs
            mountPath: /var/json_logs
          - name: errorlogs
            mountPath: /var/error_logs
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: jsonlogs
          hostPath:
            path: /var/json_logs
        - name: errorlogs
          hostPath:
            path: /var/error_logs
---
 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
 
---
 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: elastic-system
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
 
---
 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
`

**Comment by anthonynguyen394** [comment]
I am having this problem as well, and I can confirm that I am not using external config file. I can also confirm that there is data duplication. I am using the Autodiscover feature with Filebeat v8.6.2. Here is my filebeat.yaml:

```
apiVersion: beat.k8s.elastic.co/v1beta1`
kind: Beat
metadata:
  name: file
spec:
  type: filebeat
  version: 8.6.2
  config:
    logging.metrics.enabled: false
    filebeat:
      autodiscover:
        providers:
          - type: kubernetes
            templates:
              - condition:
                  and: 
                    - regexp:
                        kubernetes.namespace: "^<namespace>-*"
                    - not:
                        regexp:
                          kubernetes.pod.name: "^<pod name>-*"
                config:
                  - type: filestream
                    id: core-container-logs
                    paths:
                      - /var/log/containers/*-${data.kubernetes.container.id}.log
                    parsers:
                      - multiline:
                          type: pattern
                          # Match date pattern of 2023:03:16:13:23:49 at beginning of each log line
                          pattern: '^[0-9]{4}:[0-9]{2}:[0-9]{2}:[0-9]{2}:[0-9]{2}:[0-9]{2}'
                          negate: true
                          match: after
    processors:
      - drop_fields:
          fields: 
            - "/kubernetes.node.labels.*/"
            - "/kubernetes.namespace_labels.*/"
            - "/kubernetes.labels.*/"
            - "/agent.*/"
            - "/host.*/"
            - "/input.*/"
            - "/ecs.*/"
            - "/kubernetes.namespace_uid.*/"
            - "/kubernetes.node.uid.*/"
            - "/container.runtime.*/"
            - "/log.offset.*/"
            - "/stream.*/"
          ignore_missing: true
    output.logstash:
      hosts: ["logstash.elastic-system.svc:5044"]
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        tolerations:
        - key: dedicated
          operator: Exists
          effect: NoSchedule       
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
---
 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
 
---
 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: elastic-system
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
 
---
 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
```

**Comment by cmacknz** [comment]
@anthonynguyen394 you are using a fixed id of `id: core-container-logs` in your configuration. If you use the container ID as a suffix it will hopefully solve this problem for you, for example `id: core-container-logs-${data.kubernetes.container.id}`. 

This will ensure that if Filebeat autodiscover tracks multiple instances of the same container they each end up with a unique ID.

**Comment by anthonynguyen394** [comment]
@cmacknz I did some research around and actually tried that, but still hit the same error, even though it picks up the container id.

**Comment by bigpigeon** [comment]
I got same error, my filebeat version v7.17.9, my config  section below
```
filebeat.autodiscover:
  enabled: true
  # List of enabled autodiscover providers
  providers:
  - type: kubernetes
    ...
    templates: 
      config:
      - id: stdlog_${data.kubernetes.container.id}
```
and then I got the error, and then the logs was not be collected
```
filestream input with ID 'stdlog_xxxx' already exists, this will lead to data duplication, please use a different ID
```

**Comment by belimawr** [comment]
@bigpigeon this log error is informational, it does not stop filestream's start up process, if you're curious here is the code issuing this log entry:
https://github.com/elastic/beats/blob/46a321e17b1906b4710f010d9a96d67742eb51da/filebeat/input/filestream/internal/input-logfile/manager.go#L182-L185

If logs are not being collected, you should be able to see other errors in your logs as well. If you don't see any other errors, try running on debug level with the `autodiscover` selector enabled, it will give more insights and show some other errors.

Could you share the whole filestream/autodiscovery config?

**Comment by kfperegrin** [comment]
I am seeing this in both 7.17.9 and in 8.7.0 with filestream duplicate errors:
Mar 31 16:48:46 XXXXXXXXXX filebeat: 2023-03-31T16:48:46.015-0400#011ERROR#011[input]#011input-logfile/manager.go:183#011filestream input with ID 'ansible_archive' already exists, this will lead to data duplication, please use a different ID

**Comment by belimawr** [comment]
I did some more investigation and this error message also appears when using Kubernetes autodiscovery. Here is a simple example config:
```yaml
filebeat.autodiscover:
  providers:
    - type: kubernetes
      node: ${NODE_NAME}
      hints.enabled: true
      include_annotations: true
      include_labels: true
      hints.default_config:
        prospector.scanner.symlinks: true
        id: filestream-kubernetes-pod-${data.kubernetes.container.id}
        type: filestream
        paths:
          - /var/log/containers/*${data.kubernetes.container.id}.log
        parsers:
          - container: ~
```
This configuration is correct, and all IDs are unique per container/file harvested.

The log error comes from the fact that the autodiscovery calls the `CheckConfig` from a RunnerFactory, below are some bits of code involved on this process:
https://github.com/elastic/beats/blob/786730c87477e6628e7f408e676638f36b92ee1d/libbeat/autodiscover/autodiscover.go#L234

https://github.com/elastic/beats/blob/786730c87477e6628e7f408e676638f36b92ee1d/libbeat/cfgfile/factories.go#L78-L84

https://github.com/elastic/beats/blob/786730c87477e6628e7f408e676638f36b92ee1d/filebeat/input/v2/compat/compat.go#L72-L78

`_, err := f.loader.Configure(cfg)` will instantiate an input, that on Filestream case will call the Create method from the InputManager that ends ups adding the ID to its bookkeeping even though the input will never be started stopped. Here is the code responsible for that:
https://github.com/elastic/beats/blob/786730c87477e6628e7f408e676638f36b92ee1d/filebeat/input/filestream/internal/input-logfile/manager.go#L161-L187

**Comment by kfperegrin** [comment]
Reloads are disabled.

filebeat.config.inputs:
  enabled: true
  path: inputs.d/*.yml
  reload.enabled: false
  reload.period: 60s

**Comment by belimawr** [comment]
@kfperegrin as I mentioned before, it seems you have multiple instances of filestream input configured with the same ID (`ansible_archive`). Please double check all of your configuration files.

**Comment by abraxxa** [comment]
We had a support case open for this issue and the cause for us where included files that are reloaded immediately after filebeat starts. As it still isn‘t fixes we‘re still using the type log instead of filestream.

**Comment by fixed77** [comment]
version 8.8.0, the problem is still relevant

**Comment by germain05** [comment]
> Contributor

@belimawr so what you mean is that if everything is properly configured and we still get data duplication message, it is not an issue if the data is not actually duplicated?

**Comment by belimawr** [comment]
> > Contributor
> 
> @belimawr so what you mean is that if everything is properly configured and we still get data duplication message, it is not an issue if the data is not actually duplicated?

Sorry @germain05, I didn't get what you meat. Could you elaborate it more?

**Comment by germain05** [comment]
@belimawr I have this issue: https://github.com/elastic/beats/issues/36379

> I did some more investigation and this error message also appears when using Kubernetes autodiscovery. Here is a simple example config:
> 
> ```yaml
> filebeat.autodiscover:
>   providers:
>     - type: kubernetes
>       node: ${NODE_NAME}
>       hints.enabled: true
>       include_annotations: true
>       include_labels: true
>       hints.default_config:
>         prospector.scanner.symlinks: true
>         id: filestream-kubernetes-pod-${data.kubernetes.container.id}
>         type: filestream
>         paths:
>           - /var/log/containers/*${data.kubernetes.container.id}.log
>         parsers:
>           - container: ~
> ```
> 
> This configuration is correct, and all IDs are unique per container/file harvested.
> 
> The log error comes from the fact that the autodiscovery calls the `CheckConfig` from a RunnerFactory, below are some bits of code involved on this process:
> 
> https://github.com/elastic/beats/blob/786730c87477e6628e7f408e676638f36b92ee1d/libbeat/autodiscover/autodiscover.go#L234
> 
> https://github.com/elastic/beats/blob/786730c87477e6628e7f408e676638f36b92ee1d/libbeat/cfgfile/factories.go#L78-L84
> 
> https://github.com/elastic/beats/blob/786730c87477e6628e7f408e676638f36b92ee1d/filebeat/input/v2/compat/compat.go#L72-L78
> 
> `_, err := f.loader.Configure(cfg)` will instantiate an input, that on Filestream case will call the Create method from the InputManager that ends ups adding the ID to its bookkeeping even though the input will never be started stopped. Here is the code responsible for that:
> 
> https://github.com/elastic/beats/blob/786730c87477e6628e7f408e676638f36b92ee1d/filebeat/input/filestream/internal/input-logfile/manager.go#L161-L187

I am talking about that.

to be more precise I have this issue here: https://github.com/elastic/beats/issues/36379

**Comment by germain05** [comment]
@belimawr, Please can you help here: https://github.com/elastic/beats/issues/36379?

**Comment by belimawr** [comment]
@germain05 I'm reading/responding to it right now.

**Comment by belimawr** [comment]
@germain05 I replied here: https://github.com/elastic/beats/issues/36379#issuecomment-1689553126

TL;DR: The issue should have been fixed, and so far I haven't managed to reproduce it, so I'll need some help understanding what is different on your environment.

**Comment by germain05** [comment]
@belimawr I though so also, when going through issues. Added more informations there: https://github.com/elastic/beats/issues/36379#issuecomment-1689553126

**Comment by belimawr** [comment]
I can easily reproduce it on Kubernetes with Filebeat `v8.9.2`, so I'm re-opening the issue.

It's mostly the manifest from https://www.elastic.co/guide/en/beats/filebeat/current/running-on-kubernetes.html but with small modifications in Filebeat's configuration.

Here is the kubernetes manifest I used:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups: ["apps"]
  resources:
    - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
    - jobs
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: filebeat
  # should be the namespace where filebeat is running
  namespace: kube-system
  labels:
    k8s-app: filebeat
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: filebeat-kubeadm-config
  namespace: kube-system
  labels:
    k8s-app: filebeat
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - kubeadm-config
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: filebeat
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: kube-system
roleRef:
  kind: Role
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: filebeat-kubeadm-config
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: kube-system
roleRef:
  kind: Role
  name: filebeat-kubeadm-config
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: filestream
            prospector.scanner.symlinks: true
            id: filestream-kubernetes-pod-${data.kubernetes.container.id}
            take_over: true
            paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log
            parsers:
            - container: ~ 
    processors:
      - add_cloud_metadata:
      - add_host_metadata:

    output.elasticsearch:
      hosts: ["https://localhost:9200"] # add real credentials
      protocol: "https"
      username: "elastic"
      password: "changeme"
      allow_older_versions: true
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.9.2
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: changeme
        - name: ELASTIC_CLOUD_ID
          value:
        - name: ELASTIC_CLOUD_AUTH
          value:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          # If using Red Hat OpenShift uncomment this:
          #privileged: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0640
          name: filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      # data folder stores a registry of read status for all files, so we don't send everything again on a Filebeat pod restart
      - name: data
        hostPath:
          # When filebeat runs as non-root user, this directory needs to be writable by group (g+w).
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
---

```

**Comment by belimawr** [comment]
> We are seeing the same issue as @belimawr with filebeat 8.11.1. Any workaround to resolve this? Maybe fingerprint?

The fingerprint won't help here as it is the file identity and has no influence on this log message. The filestream input is working as expected, however that log message gets incorrectly logged in some cases.

**Comment by kbujold** [comment]
> The fingerprint won't help here as it is the file identity and has no influence on this log message. The filestream input is working as expected, however that log message gets incorrectly logged in some cases.

@belimawr its more than an incorrect log, it causes the pod to crash continuously.

**Comment by belimawr** [comment]
> @belimawr its more than an incorrect log, it causes the pod to crash continuously.

Ok, then it's a bigger problem.

1. Have you managed to reproduce it on a controlled environment (Kind, Minikube, etc)? If so, could you share the configuration and steps to reproduce?
2. Can you share some debug logs that capture the crash?

**Comment by kbujold** [comment]
@belimawr Is there a work around for this issue? Other than filtering this log out?

**Comment by belimawr** [comment]
> @belimawr Is there a work around for this issue?

The incorrect logs? No at the moment there isn't any.

**Comment by kbujold** [comment]
> The incorrect logs? No at the moment there isn't any.

Yes

**Comment by PBarnard** [comment]
Just to add to this I've upgraded to filebeat `8.12.1` on AWS EKS Kubernetes and I'm still seeing this error. It's not causing any problems as far as I can tell, Filebeat still runs without crashing and all logs are ingesting into Elastic. Just thought I'd mention it :)

**Comment by barrowkwan** [comment]
same here.  running filebeat 8.14.0 in AWS EKS.  I am getting "filestream input with ID '...." already exits, this wil lead to data duplication... "  
filebeat didn't crash and I don't think I got duplicated data.

**Comment by GEownt** [comment]
Filebeat in version `8.15.0` is still having this issue.
