### ISSUE TITLE
[metricbeat/process] - Process metrics seems to be misleading

### ISSUE THREAD

**Issue by VihasMakwana** [elastic/beats#42593]
> Hi Folks, 
> seems like we are facing the same issue with metric/field `system.process.cpu.total.norm.pct`, `process.cpu.pct` and `system.process.cpu.total.pct`.
> 
> ex below = `161%` and `7,729.1%`:
> 
> <img width="743" alt="Image" src="https://github.com/user-attachments/assets/fff10031-88bd-4b56-a375-0317d8ffb5b8" />
> 
> metricbeat version: `8.17.1`
> use_performance_counters was set to `true`
> 
> 
>  I guess `system.process.cpu.total.value` is also wrong, but I'm not 100% sure. 

 _Originally posted by @apmartins85 in [#40926](https://github.com/elastic/beats/issues/40926#issuecomment-2619099355)_

**Comment by VihasMakwana** [comment]
@apmartins85 @vishal-jogi I'll be taking a look at this and keep you guys posted. Sorry for delay, I was in middle of some urgent work.

**Comment by vishal-jogi** [comment]
Thank you @VihasMakwana for the heads up. Will keep an eye on this thread for further update.

**Comment by vishal-jogi** [comment]
@VihasMakwana just checking to see if you have any update on this one?

Thank you!

**Comment by pierrehilbert** [comment]
Sorry but we don't have any updates to share on that topic for now.

**Comment by VihasMakwana** [comment]
@vishal-jogi sorry for delay as we were working on other priorities. I'm assigning this to myself and will look at this and keep you posted.

**Comment by vishal-jogi** [comment]
@VihasMakwana Thanks for the heads up, much appreciated !!

The customer is awaiting further feedback from us, so kindly keep us informed on the progress.

Thank you!

**Comment by VihasMakwana** [comment]
@vishal-jogi I tried to reproduce this on my personal windows but everything worked as expected. But I had to stop testing because my PC turned off unexpectedly and it isn't starting up.

I'll get one GCP VM and test it out. If it's still not reproducible, I'll test it out on >64 core machine and keep you posted.

**Comment by VihasMakwana** [comment]
@vishal-jogi @apmartins85 I got the issue finally. It's related to windows APIs returning lesser cores than actual cores (for machines >64 cores). I still had to get a high core VM to test the fix, but I looked at the code and got it. 
I will keep you posted on the PR.

**Comment by VihasMakwana** [comment]
@vishal-jogi @apmartins85 https://github.com/elastic/elastic-agent-system-metrics/pull/207 is up for review. Once it gets merged, I will update beats go.mod.

**Comment by VihasMakwana** [comment]
The issue is fixed (PR is yet to be merged. I'll get it merged by today). I'm attaching a few screenshots for reference:

Before:

<img width="1263" alt="Image" src="https://github.com/user-attachments/assets/ce68f539-07ac-4192-b620-5779c057337e" />

- Here, the `system.process.cpu.total.norm.pct` value is `1.248` i.e. 124.8%, which is incorrect.

After (after the fix):

<img width="1259" alt="Image" src="https://github.com/user-attachments/assets/f691d5e1-edd9-447a-8403-deb8c8671007" />

- For the same process but after my fix is applied, the `system.process.cpu.total.norm.pct` value is `0.632` i.e. 63.2%, which is correct and within acceptable range.

**Comment by apmartins85** [comment]
Hi @VihasMakwana 
I see you are merging the change on [elastic-agent-system-metrics](https://github.com/elastic/elastic-agent-system-metrics).
However, the issue was in the [metricbeat](https://github.com/elastic/beats/tree/main/metricbeat);

Are you planning to also add the fix in the metricbeat repo? Also, is it possible to release a bug fix in version 8?

**Comment by VihasMakwana** [comment]
@apmartins85 yes. https://github.com/elastic/beats/pull/43409 is the PR to bump the [elastic-agent-system-metrics](https://github.com/elastic/elastic-agent-system-metrics).

It will fix the issue.

**Comment by VihasMakwana** [comment]
> Also, is it possible to release a bug fix in version 8?

yes. it will be backported to 8.x and 9.0

**Comment by apmartins85** [comment]
@VihasMakwana 
I tried version `8.17.3` and `8.17.4`.
I'm still seeing the same issue.

**Comment by AnchalatElastic** [comment]
@VihasMakwana 
Customer tried the fix with both version `8.17.3` & `8.17.4`, and it is not working they are facing the same issue. 

They are using Azure VM

```
Operating system
:
Windows (Windows Server 2022 Datacenter)
Size
:
Standard E96ds v5 (96 vcpus, 672 GiB memory)
```




<img width="1150" alt="Image" src="https://github.com/user-attachments/assets/7dbcecce-bd5b-494a-8d28-af199d6ae69a" />


<img width="1215" alt="Image" src="https://github.com/user-attachments/assets/009be13e-e962-4baa-882a-f5ecf66d4012" />

**Metricbeat.yaml**

```
File name: gs.yaml
You can download the file here: https://upload.elastic.co/d/6775aae50773af4478f72add48f7ff21514348bcaa5802938234944fab955f15.
Use this Authorization Token: 9921014ecc41cc46
```

**Comment by PBoff** [comment]
@pierrehilbert as @VihasMakwana is on PTO can you please help re-assign this

**Comment by pierrehilbert** [comment]
Backports are not merged yet (as you can see in this issue with the four PRs created by mergify) so this is the expected behavior.
@VihasMakwana will take care of it next week.

**Comment by PBoff** [comment]
@pierrehilbert - thank you for the quick update, appreciate it..

**Comment by pierrehilbert** [comment]
You're welcome, don't hesitate if I can help with something else.

**Comment by VihasMakwana** [comment]
@PBoff @AnchalatElastic 

<img width="577" alt="Image" src="https://github.com/user-attachments/assets/29dc8ead-7918-4e92-95fe-3d31c5e73870" />

If you take a look at commit time here, it was never supposed to be a part of 8.17.4

The build candidate for 8.17.4 was released on 20th of March and feature freeze was on 18th of March, whereas my commit was merged on 22nd of March, 3 days prior to public release.

I'll merge backports now, so we can have it in 8.17.5

**Comment by AnchalatElastic** [comment]
Thanks for the information @VihasMakwana.
