### ISSUE TITLE
Filebeat occasionally gets stuck while initializing with an invalid configuration

### ISSUE THREAD

**Issue by rdner** [elastic/beats#43137]
## Problem

Instead of logging a config validation error (no `paths` setting) and exiting, we can observe invalid log messages like these:

```json
{
  "log.level": "info",
  "@timestamp": "2025-03-07T18:27:48.880+0100",
  "log.logger": "crawler",
  "log.origin": {
    "function": "github.com/elastic/beats/v7/filebeat/beater.(*crawler).Start",
    "file.name": "beater/crawler.go",
    "file.line": 71
  },
  "message": "Loading Inputs: 1",
  "service.name": "filebeat",
  "ecs.version": "1.6.0"
}
{
  "log.level": "info",
  "@timestamp": "2025-03-07T18:27:48.880+0100",
  "log.logger": "crawler",
  "log.origin": {
    "function": "github.com/elastic/beats/v7/filebeat/beater.(*crawler).startInput",
    "file.name": "beater/crawler.go",
    "file.line": 117
  },
  "message": "starting input, keys present on the config: [filebeat.inputs.0.id filebeat.inputs.0.type]",
  "service.name": "filebeat",
  "ecs.version": "1.6.0"
}
{
  "log.level": "info",
  "@timestamp": "2025-03-07T18:27:48.880+0100",
  "log.origin": {
    "function": "github.com/elastic/beats/v7/filebeat/beater.(*crawler).Stop",
    "file.name": "beater/crawler.go",
    "file.line": 155
  },
  "message": "Stopping Crawler",
  "service.name": "filebeat",
  "ecs.version": "1.6.0"
}
{
  "log.level": "info",
  "@timestamp": "2025-03-07T18:27:48.880+0100",
  "log.origin": {
    "function": "github.com/elastic/beats/v7/filebeat/beater.(*crawler).Stop",
    "file.name": "beater/crawler.go",
    "file.line": 165
  },
  "message": "Stopping 0 inputs",
  "service.name": "filebeat",
  "ecs.version": "1.6.0"
}
{
  "log.level": "info",
  "@timestamp": "2025-03-07T18:27:48.880+0100",
  "log.origin": {
    "function": "github.com/elastic/beats/v7/filebeat/beater.(*crawler).Stop",
    "file.name": "beater/crawler.go",
    "file.line": 185
  },
  "message": "Crawler stopped",
  "service.name": "filebeat",
  "ecs.version": "1.6.0"
}
{
  "log.level": "info",
  "@timestamp": "2025-03-07T18:27:48.880+0100",
  "log.logger": "registrar",
  "log.origin": {
    "function": "github.com/elastic/beats/v7/filebeat/registrar.(*Registrar).Stop",
    "file.name": "registrar/registrar.go",
    "file.line": 130
  },
  "message": "Stopping Registrar",
  "service.name": "filebeat",
  "ecs.version": "1.6.0"
}
{
  "log.level": "debug",
  "@timestamp": "2025-03-07T18:27:48.880+0100",
  "log.logger": "registrar",
  "log.origin": {
    "function": "github.com/elastic/beats/v7/filebeat/registrar.(*Registrar).Run",
    "file.name": "registrar/registrar.go",
    "file.line": 138
  },
  "message": "Starting Registrar",
  "service.name": "filebeat",
  "ecs.version": "1.6.0"
}
{
  "log.level": "info",
  "@timestamp": "2025-03-07T18:27:48.880+0100",
  "log.logger": "registrar",
  "log.origin": {
    "function": "github.com/elastic/beats/v7/filebeat/registrar.(*Registrar).Run",
    "file.name": "registrar/registrar.go",
    "file.line": 166
  },
  "message": "Ending Registrar",
  "service.name": "filebeat",
  "ecs.version": "1.6.0"
}
{
  "log.level": "debug",
  "@timestamp": "2025-03-07T18:27:48.880+0100",
  "log.logger": "registrar",
  "log.origin": {
    "function": "github.com/elastic/beats/v7/filebeat/registrar.(*Registrar).Run",
    "file.name": "registrar/registrar.go",
    "file.line": 167
  },
  "message": "Stopping Registrar",
  "service.name": "filebeat",
  "ecs.version": "1.6.0"
}
{
  "log.level": "info",
  "@timestamp": "2025-03-07T18:27:48.880+0100",
  "log.logger": "registrar",
  "log.origin": {
    "function": "github.com/elastic/beats/v7/filebeat/registrar.(*Registrar).Stop",
    "file.name": "registrar/registrar.go",
    "file.line": 135
  },
  "message": "Registrar stopped",
  "service.name": "filebeat",
  "ecs.version": "1.6.0"
}
```

Likely there is a race condition while shutting down Filbeat due to an error from input creation.

## Steps to reproduce

Because it's a concurrency issue, it's not trivial to reproduce it.

I managed to reproduce this issue running the Filebeat binary with an invalid config in a loop using this script:

run.sh
```sh
#!/bin/bash

set -e

FILEBEAT_ROOT=/path/to/filebeat/folder
CONFIG_PATH=/path/to/config/file
ITERATIONS=$1

echo "Compiling..."

cd $FILEBEAT_ROOT
rm -f ./filebeat
go build
cd -

echo "Running $ITERATIONS times..."

for i in $(seq 1 $ITERATIONS);
do
		echo "Iteration $i>>>"
		$FILEBEAT_ROOT/filebeat run -e -c $CONFIG_PATH 2> output.json || echo "Failed as expected"
		echo "Iteration $i<<<"
		echo
done

echo "Test successfully finished"


```

with this configuration file (no `paths` in the input which makes it invalid on purpose):

filebeat.yml
```yaml
filebeat.inputs:
  - type: filestream
    id: my-filestream-id
path.data: "/path/to/data/directory"
output.console:
  enabled: true
```

I ran it for 10000 iterations using:

```sh
./run.sh 10000
```

And sometimes I hit a Filebeat process that got stuck in what seems to be a deadlock state. It cannot be interrupted and only `kill -9` can stop it.

In order to collect the logs of the stuck process you need to execute `kill -9` of the running bash script first and then on the stuck Filebeat. Then the logs of the most recent Filebeat process can be found in `output.json`.

If the bug cannot be caught on 10000 iteration, increase it to a higher number.

After the issue is found and fixed, this PR with a skipped test that detected the issue needs to be reverted https://github.com/elastic/beats/pull/42780

**Comment by mauri870** [comment]
I was unable to reproduce this on linux/amd64. I tried to simplify the reproducer with stress but it also does not fail for me:

```bash
$ cd x-pack/filebeat
$ go build .
$ go run golang.org/x/tools/cmd/stress@latest -p 1 -ignore 'no path is configured accessing' ./filebeat run -e -c ./test.yml
```

Building with -race and then running the reproducer does not show any data races as well.

**Comment by AndersonQ** [comment]
hey I believe if [this error](https://buildkite.com/elastic/filebeat/builds/14799/canvas?jid=01958ec4-13c3-4674-82e2-68fa3698f612) isn't related. It's a python test checking the right error when an invalid config is provided. The multiline pattern is missing in the config. [This is the test](https://github.com/elastic/beats/blob/f2ae2819927c44487305f370edb1e143b047a5c5/filebeat/tests/system/test_multiline.py#L344)

**Comment by rdner** [comment]
> I was unable to reproduce this on linux/amd64. I tried to simplify the reproducer with stress but it also does not fail for me:
> 
> $ cd x-pack/filebeat
> $ go build .
> $ go run golang.org/x/tools/cmd/stress@latest -p 1 -ignore 'no path is configured accessing' ./filebeat run -e -c ./test.yml
> Building with -race and then running the reproducer does not show any data races as well.

any luck if you use 100000 iterations with the original script in the description. Since it's a concurrency issue, there is no guarantee it would show up every time. I ran it in the background and checked on it once in a while until it got stuck.

**Comment by mauri870** [comment]
I tried again and it got stuck on iteration 4230. Seems to be extremely difficult to reproduce. If I run with race nothing gets reported.

**Comment by mauri870** [comment]
I revisited this for a short moment. By running the reproducer shared by Denis I managed to get one of the filebeat processes stuck, it appears to have deadlocked, but I'm pretty sure the Go runtime would yield at us in that case, so it is likely some sort of soft lock.

By following the guidelines for [CoreDumpDebugging](https://go.dev/wiki/CoreDumpDebugging) I managed to get a core dump and subsequent goroutine dump of the affected process. All goroutines are parked at that point, with some waiting on channels or semaphores. 

I’d appreciate it if someone more knowledgeable about Filebeat could take a look and see if they can spot anything wrong in this dump.

```bash
$ gcore filebeat-pid-here
$ echo "goroutines -t" | dlv core ./filebeat-binary core.471359 --allow-non-terminal-interactive=true | tee dump.txt
```

<details>
<summary>dump.txt</summary>

```txt
Type 'help' for list of commands.
(dlv)   Goroutine 1 - User: /home/mauri870/git/go/src/runtime/sema.go:110 sync.runtime_SemacquireWaitGroup (0x2ce90a5) [GC worker (idle) 2704408637363]
         0  0x0000000002ce754e in runtime.gopark
             at /home/mauri870/git/go/src/runtime/proc.go:459
         1  0x0000000002cc3dfd in runtime.goparkunlock
             at /home/mauri870/git/go/src/runtime/proc.go:464
         2  0x0000000002cc3dfd in runtime.semacquire1
             at /home/mauri870/git/go/src/runtime/sema.go:188
         3  0x0000000002ce90a5 in sync.runtime_SemacquireWaitGroup
             at /home/mauri870/git/go/src/runtime/sema.go:110
         4  0x0000000002cff568 in sync.(*WaitGroup).Wait
             at /home/mauri870/git/go/src/sync/waitgroup.go:118
         5  0x0000000005af3dbe in github.com/elastic/beats/v7/libbeat/statestore.(*Registry).Close
             at /home/mauri870/git/elastic/beats/libbeat/statestore/registry.go:52
         6  0x0000000005bc7685 in github.com/elastic/beats/v7/filebeat/beater.(*filebeatStore).Close
             at /home/mauri870/git/elastic/beats/filebeat/beater/store.go:86
         7  0x0000000005bc7685 in github.com/elastic/beats/v7/filebeat/beater.(*Filebeat).Run.deferwrap1
             at /home/mauri870/git/elastic/beats/filebeat/beater/filebeat.go:310
         8  0x0000000002cab23e in runtime.deferreturn
             at /home/mauri870/git/go/src/runtime/panic.go:589
         9  0x0000000005bc6005 in github.com/elastic/beats/v7/filebeat/beater.(*Filebeat).Run
             at /home/mauri870/git/elastic/beats/filebeat/beater/filebeat.go:539
        10  0x0000000005ad1083 in github.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).launch
             at /home/mauri870/git/elastic/beats/libbeat/cmd/instance/beat.go:758
        (truncated)
  Goroutine 2 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [force gc (idle) 8064387938556]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002cafcf3 in runtime.goparkunlock
            at /home/mauri870/git/go/src/runtime/proc.go:464
        2  0x0000000002cafcf3 in runtime.forcegchelper
            at /home/mauri870/git/go/src/runtime/proc.go:371
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 3 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC sweep wait]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c95cff in runtime.goparkunlock
            at /home/mauri870/git/go/src/runtime/proc.go:464
        2  0x0000000002c95cff in runtime.bgsweep
            at /home/mauri870/git/go/src/runtime/mgcsweep.go:316
            at /home/mauri870/git/go/src/runtime/mgc.go:203
            at /home/mauri870/git/go/src/runtime/mgc.go:203
        4  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 4 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC scavenge wait]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c935a9 in runtime.goparkunlock
            at /home/mauri870/git/go/src/runtime/proc.go:464
        2  0x0000000002c935a9 in runtime.(*scavengerState).park
            at /home/mauri870/git/go/src/runtime/mgcscavenge.go:425
        3  0x0000000002c93b59 in runtime.bgscavenge
            at /home/mauri870/git/go/src/runtime/mgcscavenge.go:658
        4  0x0000000002c89e65 in runtime.gcenable.gowrap2
            at /home/mauri870/git/go/src/runtime/mgc.go:204
        5  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 5 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [finalizer wait 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c88e87 in runtime.runFinalizersAndCleanups
            at /home/mauri870/git/go/src/runtime/mfinal.go:197
        2  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 6 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 7 - User: /home/mauri870/gopath/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 go.opencensus.io/stats/view.(*worker).start (0x6dad25f) [select]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002cc2ae5 in runtime.selectgo
            at /home/mauri870/git/go/src/runtime/select.go:351
        2  0x0000000006dad25f in go.opencensus.io/stats/view.(*worker).start
            at /home/mauri870/gopath/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292
        3  0x0000000006dac485 in go.opencensus.io/stats/view.init.0.gowrap1
            at /home/mauri870/gopath/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34
        4  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 8 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [chan receive]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c79d6e in runtime.chanrecv
            at /home/mauri870/git/go/src/runtime/chan.go:664
        2  0x0000000002c798f2 in runtime.chanrecv1
            at /home/mauri870/git/go/src/runtime/chan.go:506
        3  0x0000000002c8d02f in runtime.unique_runtime_registerUniqueMapCleanup.func2
            at /home/mauri870/git/go/src/runtime/mgc.go:1804
        4  0x0000000002c8d02f in runtime.unique_runtime_registerUniqueMapCleanup.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1807
        5  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 18 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 19 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 20 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 21 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
  Goroutine 22 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 23 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 24 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 25 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 26 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 27 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 28 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 29 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 30 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 31 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 32 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 33 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 34 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 35 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 36 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 37 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704373076915]
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 38 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 8064387938556]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 39 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704408637363]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 41 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 42 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 6914385103136]
        0  0x0000000002ce754e in runtime.gopark
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 43 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 44 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 8064387938556]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 45 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 8064387938556]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 46 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 2704388504318]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 47 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 8064387938556]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 48 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [GC mark termination 8064387938556]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c8c349 in runtime.gcBgMarkWorker
            at /home/mauri870/git/go/src/runtime/mgc.go:1431
        2  0x0000000002c8c225 in runtime.gcBgMarkStartWorkers.gowrap1
            at /home/mauri870/git/go/src/runtime/mgc.go:1347
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 71 - User: /home/mauri870/git/elastic/beats/libbeat/publisher/pipeline/consumer.go:161 github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*eventConsumer).run (0x387635f) [select 2704408637363]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002cc2ae5 in runtime.selectgo
            at /home/mauri870/git/go/src/runtime/select.go:351
        2  0x000000000387635f in github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*eventConsumer).run
            at /home/mauri870/git/elastic/beats/libbeat/publisher/pipeline/consumer.go:161
        3  0x0000000003875fc9 in github.com/elastic/beats/v7/libbeat/publisher/pipeline.newEventConsumer.func1
            at /home/mauri870/git/elastic/beats/libbeat/publisher/pipeline/consumer.go:91
        4  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 72 - User: /home/mauri870/git/elastic/beats/libbeat/publisher/queue/memqueue/broker.go:272 github.com/elastic/beats/v7/libbeat/publisher/queue/memqueue.(*broker).Get (0x37fe310) [select 2704408637363]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002cc2ae5 in runtime.selectgo
            at /home/mauri870/git/go/src/runtime/select.go:351
        2  0x00000000037fe310 in github.com/elastic/beats/v7/libbeat/publisher/queue/memqueue.(*broker).Get
            at /home/mauri870/git/elastic/beats/libbeat/publisher/queue/memqueue/broker.go:272
        3  0x000000000387a393 in github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*queueReader).run
            at /home/mauri870/git/elastic/beats/libbeat/publisher/pipeline/queue_reader.go:57
        4  0x0000000003875f45 in github.com/elastic/beats/v7/libbeat/publisher/pipeline.newEventConsumer.gowrap1
            at /home/mauri870/git/elastic/beats/libbeat/publisher/pipeline/consumer.go:102
        5  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 73 - User: /home/mauri870/git/elastic/beats/libbeat/publisher/queue/memqueue/runloop.go:127 github.com/elastic/beats/v7/libbeat/publisher/queue/memqueue.(*runLoop).runIteration (0x37ffa56) [select 2704408637363]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002cc2ae5 in runtime.selectgo
            at /home/mauri870/git/go/src/runtime/select.go:351
        2  0x00000000037ffa56 in github.com/elastic/beats/v7/libbeat/publisher/queue/memqueue.(*runLoop).runIteration
            at /home/mauri870/git/elastic/beats/libbeat/publisher/queue/memqueue/runloop.go:127
        3  0x00000000037ff81f in github.com/elastic/beats/v7/libbeat/publisher/queue/memqueue.(*runLoop).run
            at /home/mauri870/git/elastic/beats/libbeat/publisher/queue/memqueue/runloop.go:94
        4  0x00000000037fdad0 in github.com/elastic/beats/v7/libbeat/publisher/queue/memqueue.NewQueue.func1
            at /home/mauri870/git/elastic/beats/libbeat/publisher/queue/memqueue/broker.go:168
        5  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 74 - User: /home/mauri870/git/elastic/beats/libbeat/publisher/queue/memqueue/ackloop.go:42 github.com/elastic/beats/v7/libbeat/publisher/queue/memqueue.(*ackLoop).run (0x37fcf65) [select 2704408637363]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002cc2ae5 in runtime.selectgo
            at /home/mauri870/git/go/src/runtime/select.go:351
        2  0x00000000037fcf65 in github.com/elastic/beats/v7/libbeat/publisher/queue/memqueue.(*ackLoop).run
            at /home/mauri870/git/elastic/beats/libbeat/publisher/queue/memqueue/ackloop.go:42
        3  0x00000000037fd9f0 in github.com/elastic/beats/v7/libbeat/publisher/queue/memqueue.NewQueue.func2
            at /home/mauri870/git/elastic/beats/libbeat/publisher/queue/memqueue/broker.go:172
        4  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 82 - User: /home/mauri870/git/elastic/beats/libbeat/publisher/pipeline/client_worker.go:92 github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*clientWorker).run (0x387532e) [select 2704408637363]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002cc2ae5 in runtime.selectgo
            at /home/mauri870/git/go/src/runtime/select.go:351
        2  0x000000000387532e in github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*clientWorker).run
            at /home/mauri870/git/elastic/beats/libbeat/publisher/pipeline/client_worker.go:92
        3  0x00000000038751cd in github.com/elastic/beats/v7/libbeat/publisher/pipeline.makeClientWorker.gowrap1
            at /home/mauri870/git/elastic/beats/libbeat/publisher/pipeline/client_worker.go:75
        4  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 83 - User: /home/mauri870/git/elastic/beats/libbeat/monitoring/report/log/log.go:166 github.com/elastic/beats/v7/libbeat/monitoring/report/log.(*reporter).snapshotLoop (0x381372d) [select]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002cc2ae5 in runtime.selectgo
            at /home/mauri870/git/go/src/runtime/select.go:351
        2  0x000000000381372d in github.com/elastic/beats/v7/libbeat/monitoring/report/log.(*reporter).snapshotLoop
            at /home/mauri870/git/elastic/beats/libbeat/monitoring/report/log/log.go:166
        3  0x0000000003813409 in github.com/elastic/beats/v7/libbeat/monitoring/report/log.MakeReporter.func1
            at /home/mauri870/git/elastic/beats/libbeat/monitoring/report/log/log.go:139
        4  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 84 - User: /home/mauri870/git/go/src/runtime/proc.go:459 runtime.gopark (0x2ce754e) [select 2704408637363]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002cc2ae5 in runtime.selectgo
            at /home/mauri870/git/go/src/runtime/select.go:351
        2  0x0000000002ce0cd2 in runtime.ensureSigM.func1
            at /home/mauri870/git/go/src/runtime/signal_unix.go:1085
        3  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 114 - User: /home/mauri870/git/go/src/runtime/sigqueue.go:152 os/signal.signal_recv (0x2ce9b89) (thread 471367)
        0  0x0000000002cf1b03 in runtime.futex
            at /home/mauri870/git/go/src/runtime/sys_linux_amd64.s:558
        1  0x0000000002ca8b50 in runtime.futexsleep
            at /home/mauri870/git/go/src/runtime/os_linux.go:75
        2  0x0000000002c7f935 in runtime.notetsleep_internal
            at /home/mauri870/git/go/src/runtime/lock_futex.go:70
        3  0x0000000002c7fa38 in runtime.notetsleepg
            at /home/mauri870/git/go/src/runtime/lock_futex.go:124
        4  0x0000000002ce9b89 in os/signal.signal_recv
            at /home/mauri870/git/go/src/runtime/sigqueue.go:152
        5  0x0000000003313f93 in os/signal.loop
            at /home/mauri870/git/go/src/os/signal/signal_unix.go:23
        6  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 130 - User: /home/mauri870/gopath/pkg/mod/github.com/elastic/elastic-agent-libs@v0.18.9/service/service.go:50 github.com/elastic/elastic-agent-libs/service.HandleSignals.func1 (0x387de35) [chan receive 2704408637363]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c79d6e in runtime.chanrecv
            at /home/mauri870/git/go/src/runtime/chan.go:664
        2  0x0000000002c798f2 in runtime.chanrecv1
            at /home/mauri870/git/go/src/runtime/chan.go:506
        3  0x000000000387de35 in github.com/elastic/elastic-agent-libs/service.HandleSignals.func1
            at /home/mauri870/gopath/pkg/mod/github.com/elastic/elastic-agent-libs@v0.18.9/service/service.go:50
        4  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
  Goroutine 132 - User: /home/mauri870/git/elastic/beats/filebeat/beater/filebeat.go:301 github.com/elastic/beats/v7/filebeat/beater.(*Filebeat).Run.func1 (0x5bc76e6) [chan receive 2704408637363]
        0  0x0000000002ce754e in runtime.gopark
            at /home/mauri870/git/go/src/runtime/proc.go:459
        1  0x0000000002c79d6e in runtime.chanrecv
            at /home/mauri870/git/go/src/runtime/chan.go:664
        2  0x0000000002c798f2 in runtime.chanrecv1
            at /home/mauri870/git/go/src/runtime/chan.go:506
        3  0x0000000005bc76e6 in github.com/elastic/beats/v7/filebeat/beater.(*Filebeat).Run.func1
            at /home/mauri870/git/elastic/beats/filebeat/beater/filebeat.go:301
        4  0x0000000002cefce1 in runtime.goexit
            at /home/mauri870/git/go/src/runtime/asm_amd64.s:1692
[49 goroutines]
(dlv) exit
```

</details>

**Comment by mauri870** [comment]
Upon close inspection it seems obvious that there is something fishy going on when closing the store, which happens at the end of [filebeat Run](https://github.com/elastic/beats/blob/df62e10/filebeat/beater/filebeat.go#L310) in a defer statement:

https://github.com/elastic/beats/blob/1fc18c2de39b4bfd29749be15cb79c8fb0757375/libbeat/statestore/registry.go#L52

```txt
Goroutine 1 - User: /home/mauri870/git/go/src/runtime/sema.go:110 sync.runtime_SemacquireWaitGroup (0x2ce90a5) [GC worker (idle) 2704408637363]
         0  0x0000000002ce754e in runtime.gopark
             at /home/mauri870/git/go/src/runtime/proc.go:459
         1  0x0000000002cc3dfd in runtime.goparkunlock
             at /home/mauri870/git/go/src/runtime/proc.go:464
         2  0x0000000002cc3dfd in runtime.semacquire1
             at /home/mauri870/git/go/src/runtime/sema.go:188
         3  0x0000000002ce90a5 in sync.runtime_SemacquireWaitGroup
             at /home/mauri870/git/go/src/runtime/sema.go:110
         4  0x0000000002cff568 in sync.(*WaitGroup).Wait
             at /home/mauri870/git/go/src/sync/waitgroup.go:118
         5  0x0000000005af3dbe in github.com/elastic/beats/v7/libbeat/statestore.(*Registry).Close
             at /home/mauri870/git/elastic/beats/libbeat/statestore/registry.go:52
         6  0x0000000005bc7685 in github.com/elastic/beats/v7/filebeat/beater.(*filebeatStore).Close
             at /home/mauri870/git/elastic/beats/filebeat/beater/store.go:86
         7  0x0000000005bc7685 in github.com/elastic/beats/v7/filebeat/beater.(*Filebeat).Run.deferwrap1
             at /home/mauri870/git/elastic/beats/filebeat/beater/filebeat.go:310
         8  0x0000000002cab23e in runtime.deferreturn
             at /home/mauri870/git/go/src/runtime/panic.go:589
         9  0x0000000005bc6005 in github.com/elastic/beats/v7/filebeat/beater.(*Filebeat).Run
             at /home/mauri870/git/elastic/beats/filebeat/beater/filebeat.go:539
        10  0x0000000005ad1083 in github.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).launch
             at /home/mauri870/git/elastic/beats/libbeat/cmd/instance/beat.go:758
```

For some reason the registry WaitGroup is blocked forever on Wait. My guess is that there is a hole in the wait group logic somewhere.

**Comment by rdner** [comment]
I have some strange findings. 

We have this `WaitGroup` here https://github.com/elastic/beats/blob/6e3634f514fad19797d34d4f5a11fda4af45e2cf/libbeat/statestore/backend/memlog/memlog.go#L38

which never gets incremented and we always call `Wait` on an empty `WaitGroup` in `Close` https://github.com/elastic/beats/blob/6e3634f514fad19797d34d4f5a11fda4af45e2cf/libbeat/statestore/backend/memlog/memlog.go#L131-L132

I tried to remove this `WaitGroup` completely and I cannot reproduce the deadlock after 100000 iterations anymore. 

This should not happen, waiting on an empty wait group should not block. It might be an issue in the `WaitGroup` implementation then.

I'll keep testing and experimenting for a bit longer. It's possible that I'm just lucky not to hit the deadlock and removing the `WaitGroup` has not changed anything.

**Comment by mauri870** [comment]
Here is a small test that triggers a similar issue, but not quite the same stacktrace. At least with this we can debug things more easily with delve:

```go
// x-pack/filebeat/fbreceiver/receiver_test.go
func TestInvalidInput(t *testing.T) {
	getConfig := func() *Config {
		return &Config{
			Beatconfig: map[string]any{
				"filebeat": map[string]any{
					"inputs": []map[string]any{
						{
							"type":    "filestream",
							"id":      "my-filestream-id",
							"enabled": true,
						},
					},
				},
				"output": map[string]any{
					"otelconsumer": map[string]any{},
				},
				"processors": []map[string]any{},
				"path.home":  t.TempDir(),
			},
		}
	}

	zapCore := zapcore.NewCore(
		zapcore.NewJSONEncoder(zap.NewProductionEncoderConfig()),
		&zaptest.Discarder{},
		zapcore.InfoLevel,
	)
	observed, zapLogs := observer.New(zapcore.DebugLevel)

	core := zapcore.NewTee(zapCore, observed)

	factory := NewFactory()

	host := &oteltest.MockHost{}
	receiverSettings := receiver.Settings{}
	receiverSettings.Logger = zap.New(core)
	receiverSettings.ID = component.NewIDWithName(factory.Type(), "r1")

	done := make(chan struct{}, 1)
	var count atomic.Int64
	go func() {
		for range 1000 {
			rec, err := factory.CreateLogs(t.Context(), receiverSettings, getConfig(), nil)
			assert.NoError(t, err)
			assert.NoError(t, rec.Start(t.Context(), host))
			assert.NoError(t, rec.Shutdown(t.Context()))
			count.Add(1)
			assert.Equal(t, int(count.Load()), zapLogs.FilterLevelExact(zap.ErrorLevel).FilterMessageSnippet("error starting filebeat receiver").Len())
		}
		done <- struct{}{}
	}()

	select {
	case <-done:
	case <-time.After(10 * time.Second):
		stack := make([]byte, 100<<10) //100KB
		runtime.Stack(stack, true)
		t.Errorf("timed out waiting for test to complete: iteration %d: \n%s", count.Load(), stack[:bytes.IndexByte(stack, 0)])
		t.Log("last 100 logs:")
		for i := len(zapLogs.All()) - 100; i < len(zapLogs.All()); i++ {
			entry := zapLogs.All()[i]
			t.Logf("log %d: %s", i, entry.Message)
		}
	}
}
```

**Comment by belimawr** [comment]
@mauri870 I believe this has been fixed by https://github.com/elastic/beats/pull/46331. Have you had time to check it?

**Comment by rdner** [comment]
re-assigning this issue to @mauri870 since he's already done majority of work towards fixing this.

**Comment by mauri870** [comment]
> [@mauri870](https://github.com/mauri870) I believe this has been fixed by [#46331](https://github.com/elastic/beats/pull/46331). Have you had time to check it?

Apologies for the delay, I got caught up with other priorities after coming back from PTO.

Running the reproducer I shared [here](https://github.com/elastic/beats/issues/43137#issuecomment-3028608473), I can still reproduce the issue, it hangs after a couple hundred runs. But this reproducer uses beats receivers, so it might be unrelated.

I'll try reproducing it again using the original example.

**Comment by mauri870** [comment]
It appears that https://github.com/elastic/beats/pull/46331 fixed the issue. I can no longer reproduce it following the original description. When reverting to the parent commit, the issue reappears.

I'll go ahead and run some stress testing on https://github.com/elastic/beats/pull/42780 and unskip the test.
