### ISSUE TITLE
[Metricbeat] Monitoring metrics don't work when containerised

### ISSUE THREAD

**Issue by Constantin07** [elastic/beats#6620]
Hello,

I'm still getting these errors in metricbeat logs with version 6.2.3 when deployed as docker container:

```
2018-03-21T10:10:07.539Z	ERROR	instance/metrics.go:69	Error while getting memory usage: error retrieving process stats
2018-03-21T10:10:07.539Z	ERROR	instance/metrics.go:113	Error retrieving CPU percentages: error retrieving process stats
```

but there is no clue what could be the problem. I'm running an official metricbeat docker image and trying to pull stats from host.

The `metricbeat` container is run using this command:
```
docker run -d --restart=always --name metricbeat \
--net=host \
-u root \
-v /proc:/hostfs/proc:ro \
-v /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro \
-v /:/hostfs:ro \
-v /var/run/docker.sock:/var/run/docker.sock \
metricbeat:6.2.3 -system.hostfs=/hostfs
```

cat system.yml
```yml
- module: system
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    #- core
    - diskio
    #- socket
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory

- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
```

- Metricbeat version: 6.2.3
- Operating System: CoreOS Linux 1465.8.0
- Docker Client 1.10.3 (API 1.22), Docker Server 1.12.6 (API 1.24)

Any idea what could be the cause ?

**Comment by andrewkroh** [comment]
My initial guess is that it cannot find its own metrics in `/hostfs/proc` because it is pid namespaced and therefore is looking for something like 2 but when on the host the PID is very different.

This problem extends from the fact that `/hostfs` is treated as a global variable. This causes all metrics collecting code to read from `/hostfs/proc`. But the self monitoring metrics should always come from `/proc`.

@kvch Can you try to reproduce this? I think we need a test case for this, and we can discuss some possible solutions.

**Comment by andrewkroh** [comment]
@Constantin07 Just so we are on the same page I should clarify that those log messages indicate a problem with the self-monitoring feature that was added in 6.2 that let's the Beat report it's own CPU/memory/load information in the log (with a message of "Non-zero metrics in the last 30s") and to [X-Pack Monitoring](https://www.elastic.co/guide/en/kibana/6.2/beats-page.html) if [configured](https://www.elastic.co/guide/en/beats/metricbeat/current/monitoring.html).

Your regular metrics from the system module should not be affected.

**Comment by kvch** [comment]
@andrewkroh I can reproduce problem.
We definitely need a new test case for this. I think the problem should be handled in `gosigar`. However, I am not yet sure how it should be done.

**Comment by ewgRa** [comment]
How about #6641 fix?

It is just enough to run metricbeat with system.hostfs argument to reproduce problem, it is not related to docker itself.

**Comment by jsoriano** [comment]
I think a general solution without modifying gosigar could be to obtain the pid in the host from `<sigar.Procd>/self/status` (Pid field), instead of using `os.GetPid()`. This would work both with or without namespaces.

**Comment by Constantin07** [comment]
@andrewkroh yes, you are right. I do see in Elasticsearch regular metrics but the error log message to me appears misleading.

**Comment by ewgRa** [comment]
@jsoriano can you give more details about general solution?

In hostfs proc dir we have host processes, /hostfs/proc/self/status - it will be not an metricbeat process.

I will try later to check myself, but for now on I don't understand how it will work.

**Comment by jsoriano** [comment]
@ewgRa host proc dir contains all processes running in any PID namespace of the machine, this includes the one in which the metricbeat process runs. The special file `self` always refers to the process in the namespace of the procfs mount, so if metricbeat reads `<sigar.Procd>/self/status` (with host `/proc` mounted in `sigar.Procd`) it will see its status in the host namespace, what includes the pid in this namespace, that could be used in calls to gosigar, without changing `sigar.Procd`.

I say it could be a general solution because it'd also work when no namespacing is used: `sigar.Procd` would be `/proc` and this would contain the process as usual.

`self` behaviour in different namespaces is documented in [`pid_namespaces`](http://man7.org/linux/man-pages/man7/pid_namespaces.7.html) man page:
```
       Calling readlink(2) on the path /proc/self yields the process ID of
       the caller in the PID namespace of the procfs mount (i.e., the PID
       namespace of the process that mounted the procfs).  This can be use‐
       ful for introspection purposes, when a process wants to discover its
       PID in other namespaces.
```

**Comment by ewgRa** [comment]
@jsoriano thanks for brilliant idea, I made changes, it works, close to magic level :) Can you review it again? Failed CI looks like not related to my changes.

I see only two problems/limitations from this solution:

1. Hard to write test for this case, I've add simple test, that actually test not a real case itself.

2. In case if there will be wrong -system.hostfs flag (directory not exists for example), this way will fail to get metrics.

But I think this is acceptable edge cases.

**Comment by jsoriano** [comment]
Fixed by #6641

**Comment by Constantin07** [comment]
Thanks @ewgRa @jsoriano

**Comment by Camillevau** [comment]
Thanks

**Comment by andrzej-majewski** [comment]
Is there a workaround for this?

I am running 6.2.4 and issue still persist.

**Comment by grantcurell** [comment]
+1 still seeing:
2018-10-30T18:47:37.898Z        ERROR   instance/metrics.go:92  Error retrieving CPU percentages: error retrieving process stats: cannot find matching process for pid=1
2018-10-30T18:47:37.898Z        ERROR   instance/metrics.go:61  Error while getting memory usage: error retrieving process stats: cannot find matching process for pid=1
![image](https://user-images.githubusercontent.com/35169230/47742496-c5431a80-dc4a-11e8-9372-979807dc4a0c.png)

I added hostPid: true in accordance with: https://github.com/elastic/beats/issues/6734
![image](https://user-images.githubusercontent.com/35169230/47742572-ec99e780-dc4a-11e8-9782-f99b26cea780.png)

**Comment by jsoriano** [comment]
@grantcurell what version of metricbeat are you using? could you also share the configuration you are using to start it?
And what logs do you see with `hostPid: true`?  They shouldn' tbe the same as metricbeat won't have pid 1.

**Comment by jsoriano** [comment]
@grantcurell thanks for all the details.

6.2.4 didn't include yet the fix for this, you need 6.3.0 or later, in any case the `hostPid: true` workaround should work.

Regarding the other problems, it'd be great if you could confirm them with a more modern metricbeat version and open specific issues.

**Comment by grantcurell** [comment]
> @grantcurell thanks for all the details.
> 
> 6.2.4 didn't include yet the fix for this, you need 6.3.0 or later, in any case the `hostPid: true` workaround should work.
> 
> Regarding the other problems, it'd be great if you could confirm them with a more modern metricbeat version and open specific issues.

Can I update metricbeat independently of Elasticsearch in this case?

**Comment by grantcurell** [comment]
@jsoriano upgrading to 6.4.2 didn't fix the problem. I still get a bunch of strange partial data if the time interval is anything less than 30 minutes. Ex the Kubernetes dashboard:

![image](https://user-images.githubusercontent.com/35169230/47864400-7d95cd80-ddc7-11e8-9efa-a1c073c19cc7.png)

or

![image](https://user-images.githubusercontent.com/35169230/47864450-9bfbc900-ddc7-11e8-9607-c8c8ce067ea4.png)

But move it to 30 minutes and you get:

![image](https://user-images.githubusercontent.com/35169230/47864487-b3d34d00-ddc7-11e8-83fd-8686747bb9b9.png)
